// Centro de Ayuda / FAQ de DevMetrics.
// Base de conocimiento estructurada: categorías -> preguntas/respuestas.
// Cada item declara el rol más interesado y su nivel de importancia.

export type HelpRole = "Todos" | "TL" | "PO" | "Director" | "Admin";
export type HelpImportance = "alta" | "media" | "baja";
export type FeaturedGroup = "nuevos" | "TL" | "PO" | "Director" | "seguridad";

export interface FaqItem {
  id: string;
  q: string;
  a: string;
  role: HelpRole;
  importance: HelpImportance;
  featured?: FeaturedGroup[];
}

export interface FaqCategory {
  id: string;
  title: string;
  description: string;
  items: FaqItem[];
}

// Los valores son claves i18n (prefijo "faq."). El consumidor traduce con t().
export const IMPORTANCE_LABEL: Record<HelpImportance, string> = {
  alta: "faq.importance.alta",
  media: "faq.importance.media",
  baja: "faq.importance.baja",
};

export const ROLE_FILTERS: HelpRole[] = [
  "Todos",
  "TL",
  "PO",
  "Director",
  "Admin",
];

// Microcopy del buscador del Centro de Ayuda (claves i18n; traducir con t()).
export const SEARCH_PLACEHOLDER = "faq.search.placeholder";
export const SEARCH_SUBTEXT = "faq.search.subtext";
export const SEARCH_EMPTY = "faq.search.empty";

export const FAQ_INTRO = "faq.intro";

export const FAQ: FaqCategory[] = [
  {
    id: "general",
    title: "faq.cat.general.title",
    description: "faq.cat.general.desc",
    items: [
      {
        id: "gen-que-es",
        q: "faq.q.gen-que-es.q",
        a: "faq.q.gen-que-es.a",
        role: "Todos",
        importance: "alta",
        featured: ["nuevos"],
      },
      {
        id: "gen-para-que",
        q: "faq.q.gen-para-que.q",
        a: "faq.q.gen-para-que.a",
        role: "Todos",
        importance: "alta",
        featured: ["nuevos"],
      },
      {
        id: "gen-a-quien",
        q: "faq.q.gen-a-quien.q",
        a: "faq.q.gen-a-quien.a",
        role: "Todos",
        importance: "alta",
      },
      {
        id: "gen-problema",
        q: "faq.q.gen-problema.q",
        a: "faq.q.gen-problema.a",
        role: "Todos",
        importance: "alta",
      },
      {
        id: "gen-vs-jira",
        q: "faq.q.gen-vs-jira.q",
        a: "faq.q.gen-vs-jira.a",
        role: "Todos",
        importance: "alta",
        featured: ["nuevos"],
      },
      {
        id: "gen-vs-dashboards",
        q: "faq.q.gen-vs-dashboards.q",
        a: "faq.q.gen-vs-dashboards.a",
        role: "Todos",
        importance: "media",
      },
      {
        id: "gen-tipos-equipo",
        q: "faq.q.gen-tipos-equipo.q",
        a: "faq.q.gen-tipos-equipo.a",
        role: "Todos",
        importance: "media",
      },
      {
        id: "gen-agiles",
        q: "faq.q.gen-agiles.q",
        a: "faq.q.gen-agiles.a",
        role: "Todos",
        importance: "media",
      },
      {
        id: "gen-remoto",
        q: "faq.q.gen-remoto.q",
        a: "faq.q.gen-remoto.a",
        role: "Todos",
        importance: "baja",
      },
      {
        id: "gen-startups",
        q: "faq.q.gen-startups.q",
        a: "faq.q.gen-startups.a",
        role: "Director",
        importance: "media",
      },
      {
        id: "gen-tiempo-ahorro",
        q: "faq.q.gen-tiempo-ahorro.q",
        a: "faq.q.gen-tiempo-ahorro.a",
        role: "Todos",
        importance: "media",
      },
      {
        id: "gen-valor-primer-uso",
        q: "faq.q.gen-valor-primer-uso.q",
        a: "faq.q.gen-valor-primer-uso.a",
        role: "Todos",
        importance: "alta",
        featured: ["nuevos"],
      },
      {
        id: "gen-decisiones",
        q: "faq.q.gen-decisiones.q",
        a: "faq.q.gen-decisiones.a",
        role: "Todos",
        importance: "media",
      },
    ],
  },
  {
    id: "setup",
    title: "faq.cat.setup.title",
    description: "faq.cat.setup.desc",
    items: [
      {
        id: "set-cuenta",
        q: "faq.q.set-cuenta.q",
        a: "faq.q.set-cuenta.a",
        role: "Todos",
        importance: "alta",
        featured: ["nuevos"],
      },
      {
        id: "set-invitar",
        q: "faq.q.set-invitar.q",
        a: "faq.q.set-invitar.a",
        role: "Admin",
        importance: "media",
      },
      {
        id: "set-workspace",
        q: "faq.q.set-workspace.q",
        a: "faq.q.set-workspace.a",
        role: "Admin",
        importance: "media",
      },
      {
        id: "set-proyecto",
        q: "faq.q.set-proyecto.q",
        a: "faq.q.set-proyecto.a",
        role: "Admin",
        importance: "alta",
      },
      {
        id: "set-conectar",
        q: "faq.q.set-conectar.q",
        a: "faq.q.set-conectar.a",
        role: "Admin",
        importance: "alta",
        featured: ["nuevos"],
      },
      {
        id: "set-permisos",
        q: "faq.q.set-permisos.q",
        a: "faq.q.set-permisos.a",
        role: "Admin",
        importance: "alta",
        featured: ["seguridad"],
      },
      {
        id: "set-tiempo",
        q: "faq.q.set-tiempo.q",
        a: "faq.q.set-tiempo.a",
        role: "Admin",
        importance: "media",
      },
      {
        id: "set-ayuda-tecnica",
        q: "faq.q.set-ayuda-tecnica.q",
        a: "faq.q.set-ayuda-tecnica.a",
        role: "Todos",
        importance: "media",
      },
      {
        id: "set-sin-todas",
        q: "faq.q.set-sin-todas.q",
        a: "faq.q.set-sin-todas.a",
        role: "Todos",
        importance: "alta",
      },
      {
        id: "set-manual",
        q: "faq.q.set-manual.q",
        a: "faq.q.set-manual.a",
        role: "Todos",
        importance: "baja",
      },
      {
        id: "set-historicos",
        q: "faq.q.set-historicos.q",
        a: "faq.q.set-historicos.a",
        role: "Todos",
        importance: "media",
      },
      {
        id: "set-solo-jira",
        q: "faq.q.set-solo-jira.q",
        a: "faq.q.set-solo-jira.a",
        role: "Todos",
        importance: "alta",
        featured: ["nuevos"],
      },
    ],
  },
  {
    id: "integrations",
    title: "faq.cat.integrations.title",
    description: "faq.cat.integrations.desc",
    items: [
      {
        id: "int-cuales",
        q: "faq.q.int-cuales.q",
        a: "faq.q.int-cuales.a",
        role: "Admin",
        importance: "alta",
      },
      {
        id: "int-jira",
        q: "faq.q.int-jira.q",
        a: "faq.q.int-jira.a",
        role: "Admin",
        importance: "alta",
      },
      {
        id: "int-github",
        q: "faq.q.int-github.q",
        a: "faq.q.int-github.a",
        role: "Admin",
        importance: "alta",
      },
      {
        id: "int-gitlab",
        q: "faq.q.int-gitlab.q",
        a: "faq.q.int-gitlab.a",
        role: "Admin",
        importance: "media",
      },
      {
        id: "int-bitbucket",
        q: "faq.q.int-bitbucket.q",
        a: "faq.q.int-bitbucket.a",
        role: "Admin",
        importance: "media",
      },
      {
        id: "int-slack",
        q: "faq.q.int-slack.q",
        a: "faq.q.int-slack.a",
        role: "Admin",
        importance: "media",
      },
      {
        id: "int-teams",
        q: "faq.q.int-teams.q",
        a: "faq.q.int-teams.a",
        role: "Admin",
        importance: "media",
      },
      {
        id: "int-figma",
        q: "faq.q.int-figma.q",
        a: "faq.q.int-figma.a",
        role: "Admin",
        importance: "baja",
      },
      {
        id: "int-qa-cicd",
        q: "faq.q.int-qa-cicd.q",
        a: "faq.q.int-qa-cicd.a",
        role: "TL",
        importance: "media",
      },
      {
        id: "int-que-datos",
        q: "faq.q.int-que-datos.q",
        a: "faq.q.int-que-datos.a",
        role: "Admin",
        importance: "alta",
        featured: ["seguridad"],
      },
      {
        id: "int-modifica",
        q: "faq.q.int-modifica.q",
        a: "faq.q.int-modifica.a",
        role: "Admin",
        importance: "alta",
        featured: ["seguridad"],
      },
      {
        id: "int-lee-escribe",
        q: "faq.q.int-lee-escribe.q",
        a: "faq.q.int-lee-escribe.a",
        role: "Admin",
        importance: "media",
        featured: ["seguridad"],
      },
      {
        id: "int-desconecta",
        q: "faq.q.int-desconecta.q",
        a: "faq.q.int-desconecta.a",
        role: "Admin",
        importance: "media",
      },
      {
        id: "int-resync",
        q: "faq.q.int-resync.q",
        a: "faq.q.int-resync.a",
        role: "Admin",
        importance: "media",
      },
      {
        id: "int-frecuencia",
        q: "faq.q.int-frecuencia.q",
        a: "faq.q.int-frecuencia.a",
        role: "Admin",
        importance: "media",
      },
      {
        id: "int-elegir-scope",
        q: "faq.q.int-elegir-scope.q",
        a: "faq.q.int-elegir-scope.a",
        role: "Admin",
        importance: "media",
        featured: ["seguridad"],
      },
      {
        id: "int-acceso-equipo",
        q: "faq.q.int-acceso-equipo.q",
        a: "faq.q.int-acceso-equipo.a",
        role: "Admin",
        importance: "media",
      },
    ],
  },
  {
    id: "reports",
    title: "faq.cat.reports.title",
    description: "faq.cat.reports.desc",
    items: [
      {
        id: "rep-tipos",
        q: "faq.q.rep-tipos.q",
        a: "faq.q.rep-tipos.a",
        role: "Todos",
        importance: "alta",
        featured: ["nuevos"],
      },
      {
        id: "rep-generar",
        q: "faq.q.rep-generar.q",
        a: "faq.q.rep-generar.a",
        role: "Todos",
        importance: "alta",
        featured: ["nuevos"],
      },
      {
        id: "rep-diferencia-vistas",
        q: "faq.q.rep-diferencia-vistas.q",
        a: "faq.q.rep-diferencia-vistas.a",
        role: "Todos",
        importance: "alta",
      },
      {
        id: "rep-saludable",
        q: "faq.q.rep-saludable.q",
        a: "faq.q.rep-saludable.a",
        role: "Todos",
        importance: "media",
      },
      {
        id: "rep-alto-riesgo",
        q: "faq.q.rep-alto-riesgo.q",
        a: "faq.q.rep-alto-riesgo.a",
        role: "Todos",
        importance: "alta",
      },
      {
        id: "rep-pendiente",
        q: "faq.q.rep-pendiente.q",
        a: "faq.q.rep-pendiente.a",
        role: "Todos",
        importance: "baja",
      },
      {
        id: "rep-critico",
        q: "faq.q.rep-critico.q",
        a: "faq.q.rep-critico.a",
        role: "Todos",
        importance: "alta",
      },
      {
        id: "rep-interpretar",
        q: "faq.q.rep-interpretar.q",
        a: "faq.q.rep-interpretar.a",
        role: "Todos",
        importance: "alta",
        featured: ["nuevos"],
      },
      {
        id: "rep-compartir",
        q: "faq.q.rep-compartir.q",
        a: "faq.q.rep-compartir.a",
        role: "Todos",
        importance: "media",
      },
      {
        id: "rep-exportar",
        q: "faq.q.rep-exportar.q",
        a: "faq.q.rep-exportar.a",
        role: "Todos",
        importance: "media",
      },
      {
        id: "rep-programar",
        q: "faq.q.rep-programar.q",
        a: "faq.q.rep-programar.a",
        role: "Admin",
        importance: "media",
      },
      {
        id: "rep-comparar",
        q: "faq.q.rep-comparar.q",
        a: "faq.q.rep-comparar.a",
        role: "Todos",
        importance: "alta",
        featured: ["TL", "Director"],
      },
      {
        id: "rep-tendencias",
        q: "faq.q.rep-tendencias.q",
        a: "faq.q.rep-tendencias.a",
        role: "Director",
        importance: "media",
      },
      {
        id: "rep-por-entidad",
        q: "faq.q.rep-por-entidad.q",
        a: "faq.q.rep-por-entidad.a",
        role: "Todos",
        importance: "media",
      },
      {
        id: "rep-cual-primero",
        q: "faq.q.rep-cual-primero.q",
        a: "faq.q.rep-cual-primero.a",
        role: "Director",
        importance: "media",
        featured: ["Director"],
      },
      {
        id: "rep-incompletos",
        q: "faq.q.rep-incompletos.q",
        a: "faq.q.rep-incompletos.a",
        role: "Admin",
        importance: "media",
      },
      {
        id: "rep-falla",
        q: "faq.q.rep-falla.q",
        a: "faq.q.rep-falla.a",
        role: "Admin",
        importance: "media",
      },
    ],
  },
  {
    id: "metrics",
    title: "faq.cat.metrics.title",
    description: "faq.cat.metrics.desc",
    items: [
      {
        id: "met-completion",
        q: "faq.q.met-completion.q",
        a: "faq.q.met-completion.a",
        role: "PO",
        importance: "alta",
      },
      {
        id: "met-velocity",
        q: "faq.q.met-velocity.q",
        a: "faq.q.met-velocity.a",
        role: "PO",
        importance: "alta",
      },
      {
        id: "met-throughput",
        q: "faq.q.met-throughput.q",
        a: "faq.q.met-throughput.a",
        role: "TL",
        importance: "media",
      },
      {
        id: "met-lead-time",
        q: "faq.q.met-lead-time.q",
        a: "faq.q.met-lead-time.a",
        role: "PO",
        importance: "media",
      },
      {
        id: "met-cycle-time",
        q: "faq.q.met-cycle-time.q",
        a: "faq.q.met-cycle-time.a",
        role: "TL",
        importance: "media",
      },
      {
        id: "met-wip",
        q: "faq.q.met-wip.q",
        a: "faq.q.met-wip.a",
        role: "TL",
        importance: "media",
      },
      {
        id: "met-scope-creep",
        q: "faq.q.met-scope-creep.q",
        a: "faq.q.met-scope-creep.a",
        role: "PO",
        importance: "alta",
        featured: ["PO"],
      },
      {
        id: "met-bloqueadas",
        q: "faq.q.met-bloqueadas.q",
        a: "faq.q.met-bloqueadas.a",
        role: "TL",
        importance: "alta",
        featured: ["TL"],
      },
      {
        id: "met-arrastradas",
        q: "faq.q.met-arrastradas.q",
        a: "faq.q.met-arrastradas.a",
        role: "PO",
        importance: "media",
      },
      {
        id: "met-bugs",
        q: "faq.q.met-bugs.q",
        a: "faq.q.met-bugs.a",
        role: "TL",
        importance: "media",
      },
      {
        id: "met-prs-abiertos",
        q: "faq.q.met-prs-abiertos.q",
        a: "faq.q.met-prs-abiertos.a",
        role: "TL",
        importance: "media",
      },
      {
        id: "met-prs-merge",
        q: "faq.q.met-prs-merge.q",
        a: "faq.q.met-prs-merge.a",
        role: "TL",
        importance: "baja",
      },
      {
        id: "met-review-time",
        q: "faq.q.met-review-time.q",
        a: "faq.q.met-review-time.a",
        role: "TL",
        importance: "alta",
        featured: ["TL"],
      },
      {
        id: "met-coverage",
        q: "faq.q.met-coverage.q",
        a: "faq.q.met-coverage.a",
        role: "TL",
        importance: "media",
      },
      {
        id: "met-build-failures",
        q: "faq.q.met-build-failures.q",
        a: "faq.q.met-build-failures.a",
        role: "TL",
        importance: "media",
      },
      {
        id: "met-deploy-failures",
        q: "faq.q.met-deploy-failures.q",
        a: "faq.q.met-deploy-failures.a",
        role: "TL",
        importance: "media",
      },
      {
        id: "met-incidentes",
        q: "faq.q.met-incidentes.q",
        a: "faq.q.met-incidentes.a",
        role: "Director",
        importance: "media",
      },
      {
        id: "met-reabiertas",
        q: "faq.q.met-reabiertas.q",
        a: "faq.q.met-reabiertas.a",
        role: "PO",
        importance: "media",
        featured: ["PO"],
      },
      {
        id: "met-score-salud",
        q: "faq.q.met-score-salud.q",
        a: "faq.q.met-score-salud.a",
        role: "Director",
        importance: "alta",
        featured: ["Director"],
      },
      {
        id: "met-riesgo-sprint",
        q: "faq.q.met-riesgo-sprint.q",
        a: "faq.q.met-riesgo-sprint.a",
        role: "TL",
        importance: "alta",
      },
      {
        id: "met-predictibilidad",
        q: "faq.q.met-predictibilidad.q",
        a: "faq.q.met-predictibilidad.a",
        role: "Director",
        importance: "alta",
        featured: ["Director"],
      },
      {
        id: "met-participacion",
        q: "faq.q.met-participacion.q",
        a: "faq.q.met-participacion.a",
        role: "TL",
        importance: "media",
      },
      {
        id: "met-comunicacion-bloqueos",
        q: "faq.q.met-comunicacion-bloqueos.q",
        a: "faq.q.met-comunicacion-bloqueos.a",
        role: "TL",
        importance: "media",
      },
      {
        id: "met-performance-individual",
        q: "faq.q.met-performance-individual.q",
        a: "faq.q.met-performance-individual.a",
        role: "TL",
        importance: "alta",
        featured: ["TL"],
      },
    ],
  },
  {
    id: "alerts",
    title: "faq.cat.alerts.title",
    description: "faq.cat.alerts.desc",
    items: [
      {
        id: "ale-que-son",
        q: "faq.q.ale-que-son.q",
        a: "faq.q.ale-que-son.a",
        role: "Todos",
        importance: "alta",
      },
      {
        id: "ale-como-generan",
        q: "faq.q.ale-como-generan.q",
        a: "faq.q.ale-como-generan.a",
        role: "Todos",
        importance: "media",
      },
      {
        id: "ale-alto-riesgo",
        q: "faq.q.ale-alto-riesgo.q",
        a: "faq.q.ale-alto-riesgo.a",
        role: "Todos",
        importance: "alta",
      },
      {
        id: "ale-critica",
        q: "faq.q.ale-critica.q",
        a: "faq.q.ale-critica.a",
        role: "Todos",
        importance: "alta",
      },
      {
        id: "ale-recurrente",
        q: "faq.q.ale-recurrente.q",
        a: "faq.q.ale-recurrente.a",
        role: "TL",
        importance: "media",
      },
      {
        id: "ale-prioridad",
        q: "faq.q.ale-prioridad.q",
        a: "faq.q.ale-prioridad.a",
        role: "Director",
        importance: "media",
      },
      {
        id: "ale-resolver",
        q: "faq.q.ale-resolver.q",
        a: "faq.q.ale-resolver.a",
        role: "Todos",
        importance: "media",
      },
      {
        id: "ale-quien-revisa",
        q: "faq.q.ale-quien-revisa.q",
        a: "faq.q.ale-quien-revisa.a",
        role: "Todos",
        importance: "media",
      },
      {
        id: "ale-no-atendida",
        q: "faq.q.ale-no-atendida.q",
        a: "faq.q.ale-no-atendida.a",
        role: "Todos",
        importance: "media",
      },
      {
        id: "ale-personalizar",
        q: "faq.q.ale-personalizar.q",
        a: "faq.q.ale-personalizar.a",
        role: "Admin",
        importance: "baja",
      },
      {
        id: "ale-sprint-riesgo",
        q: "faq.q.ale-sprint-riesgo.q",
        a: "faq.q.ale-sprint-riesgo.a",
        role: "TL",
        importance: "alta",
      },
      {
        id: "ale-detectar-bloqueos",
        q: "faq.q.ale-detectar-bloqueos.q",
        a: "faq.q.ale-detectar-bloqueos.a",
        role: "TL",
        importance: "alta",
        featured: ["TL"],
      },
      {
        id: "ale-deterioro",
        q: "faq.q.ale-deterioro.q",
        a: "faq.q.ale-deterioro.a",
        role: "TL",
        importance: "media",
      },
      {
        id: "ale-tecnico-vs-producto",
        q: "faq.q.ale-tecnico-vs-producto.q",
        a: "faq.q.ale-tecnico-vs-producto.a",
        role: "Todos",
        importance: "media",
      },
      {
        id: "ale-escalar",
        q: "faq.q.ale-escalar.q",
        a: "faq.q.ale-escalar.a",
        role: "Director",
        importance: "media",
      },
    ],
  },
  {
    id: "role-tl",
    title: "faq.cat.role-tl.title",
    description: "faq.cat.role-tl.desc",
    items: [
      {
        id: "tl-primero",
        q: "faq.q.tl-primero.q",
        a: "faq.q.tl-primero.a",
        role: "TL",
        importance: "alta",
        featured: ["TL"],
      },
      {
        id: "tl-reportes-tecnicos",
        q: "faq.q.tl-reportes-tecnicos.q",
        a: "faq.q.tl-reportes-tecnicos.a",
        role: "TL",
        importance: "media",
      },
      {
        id: "tl-deuda",
        q: "faq.q.tl-deuda.q",
        a: "faq.q.tl-deuda.a",
        role: "TL",
        importance: "media",
      },
      {
        id: "tl-prs-demorados",
        q: "faq.q.tl-prs-demorados.q",
        a: "faq.q.tl-prs-demorados.a",
        role: "TL",
        importance: "alta",
        featured: ["TL"],
      },
      {
        id: "tl-bloqueos",
        q: "faq.q.tl-bloqueos.q",
        a: "faq.q.tl-bloqueos.a",
        role: "TL",
        importance: "alta",
      },
      {
        id: "tl-acompanamiento",
        q: "faq.q.tl-acompanamiento.q",
        a: "faq.q.tl-acompanamiento.a",
        role: "TL",
        importance: "alta",
        featured: ["TL"],
      },
      {
        id: "tl-calidad",
        q: "faq.q.tl-calidad.q",
        a: "faq.q.tl-calidad.a",
        role: "TL",
        importance: "media",
      },
      {
        id: "tl-ceremonias",
        q: "faq.q.tl-ceremonias.q",
        a: "faq.q.tl-ceremonias.a",
        role: "TL",
        importance: "media",
      },
    ],
  },
  {
    id: "role-po",
    title: "faq.cat.role-po.title",
    description: "faq.cat.role-po.desc",
    items: [
      {
        id: "po-valor",
        q: "faq.q.po-valor.q",
        a: "faq.q.po-valor.a",
        role: "PO",
        importance: "alta",
        featured: ["PO"],
      },
      {
        id: "po-scope-creep",
        q: "faq.q.po-scope-creep.q",
        a: "faq.q.po-scope-creep.a",
        role: "PO",
        importance: "alta",
        featured: ["PO"],
      },
      {
        id: "po-refinamiento",
        q: "faq.q.po-refinamiento.q",
        a: "faq.q.po-refinamiento.a",
        role: "PO",
        importance: "media",
      },
      {
        id: "po-reabiertas",
        q: "faq.q.po-reabiertas.q",
        a: "faq.q.po-reabiertas.a",
        role: "PO",
        importance: "media",
      },
      {
        id: "po-backlog",
        q: "faq.q.po-backlog.q",
        a: "faq.q.po-backlog.a",
        role: "PO",
        importance: "media",
      },
      {
        id: "po-demo",
        q: "faq.q.po-demo.q",
        a: "faq.q.po-demo.a",
        role: "PO",
        importance: "baja",
      },
      {
        id: "po-riesgos-producto",
        q: "faq.q.po-riesgos-producto.q",
        a: "faq.q.po-riesgos-producto.a",
        role: "PO",
        importance: "alta",
      },
      {
        id: "po-stakeholders",
        q: "faq.q.po-stakeholders.q",
        a: "faq.q.po-stakeholders.a",
        role: "PO",
        importance: "media",
        featured: ["PO"],
      },
    ],
  },
  {
    id: "role-dir",
    title: "faq.cat.role-dir.title",
    description: "faq.cat.role-dir.desc",
    items: [
      {
        id: "dir-vista",
        q: "faq.q.dir-vista.q",
        a: "faq.q.dir-vista.a",
        role: "Director",
        importance: "alta",
        featured: ["Director"],
      },
      {
        id: "dir-semaforo",
        q: "faq.q.dir-semaforo.q",
        a: "faq.q.dir-semaforo.a",
        role: "Director",
        importance: "alta",
        featured: ["Director"],
      },
      {
        id: "dir-proyectos-riesgo",
        q: "faq.q.dir-proyectos-riesgo.q",
        a: "faq.q.dir-proyectos-riesgo.a",
        role: "Director",
        importance: "alta",
      },
      {
        id: "dir-previsibilidad",
        q: "faq.q.dir-previsibilidad.q",
        a: "faq.q.dir-previsibilidad.a",
        role: "Director",
        importance: "media",
        featured: ["Director"],
      },
      {
        id: "dir-tendencias",
        q: "faq.q.dir-tendencias.q",
        a: "faq.q.dir-tendencias.a",
        role: "Director",
        importance: "media",
      },
      {
        id: "dir-decisiones",
        q: "faq.q.dir-decisiones.q",
        a: "faq.q.dir-decisiones.a",
        role: "Director",
        importance: "media",
      },
      {
        id: "dir-compartir",
        q: "faq.q.dir-compartir.q",
        a: "faq.q.dir-compartir.a",
        role: "Director",
        importance: "media",
      },
      {
        id: "dir-multi-equipo",
        q: "faq.q.dir-multi-equipo.q",
        a: "faq.q.dir-multi-equipo.a",
        role: "Director",
        importance: "alta",
        featured: ["Director"],
      },
    ],
  },
  {
    id: "people",
    title: "faq.cat.people.title",
    description: "faq.cat.people.desc",
    items: [
      {
        id: "peo-como-analiza",
        q: "faq.q.peo-como-analiza.q",
        a: "faq.q.peo-como-analiza.a",
        role: "TL",
        importance: "alta",
      },
      {
        id: "peo-evalua-auto",
        q: "faq.q.peo-evalua-auto.q",
        a: "faq.q.peo-evalua-auto.a",
        role: "TL",
        importance: "alta",
        featured: ["TL"],
      },
      {
        id: "peo-datos",
        q: "faq.q.peo-datos.q",
        a: "faq.q.peo-datos.a",
        role: "TL",
        importance: "media",
        featured: ["seguridad"],
      },
      {
        id: "peo-injustas",
        q: "faq.q.peo-injustas.q",
        a: "faq.q.peo-injustas.a",
        role: "TL",
        importance: "alta",
      },
      {
        id: "peo-destacadas",
        q: "faq.q.peo-destacadas.q",
        a: "faq.q.peo-destacadas.a",
        role: "TL",
        importance: "media",
      },
      {
        id: "peo-podrian-mas",
        q: "faq.q.peo-podrian-mas.q",
        a: "faq.q.peo-podrian-mas.a",
        role: "TL",
        importance: "media",
      },
      {
        id: "peo-necesitan-apoyo",
        q: "faq.q.peo-necesitan-apoyo.q",
        a: "faq.q.peo-necesitan-apoyo.a",
        role: "TL",
        importance: "alta",
        featured: ["TL"],
      },
      {
        id: "peo-baja-participacion",
        q: "faq.q.peo-baja-participacion.q",
        a: "faq.q.peo-baja-participacion.a",
        role: "TL",
        importance: "media",
      },
      {
        id: "peo-contexto",
        q: "faq.q.peo-contexto.q",
        a: "faq.q.peo-contexto.a",
        role: "TL",
        importance: "alta",
      },
      {
        id: "peo-feedback",
        q: "faq.q.peo-feedback.q",
        a: "faq.q.peo-feedback.a",
        role: "TL",
        importance: "media",
      },
      {
        id: "peo-1a1",
        q: "faq.q.peo-1a1.q",
        a: "faq.q.peo-1a1.a",
        role: "TL",
        importance: "media",
        featured: ["TL"],
      },
      {
        id: "peo-privacidad",
        q: "faq.q.peo-privacidad.q",
        a: "faq.q.peo-privacidad.a",
        role: "Admin",
        importance: "alta",
        featured: ["seguridad"],
      },
      {
        id: "peo-no-castigo",
        q: "faq.q.peo-no-castigo.q",
        a: "faq.q.peo-no-castigo.a",
        role: "TL",
        importance: "alta",
      },
      {
        id: "peo-evolucion",
        q: "faq.q.peo-evolucion.q",
        a: "faq.q.peo-evolucion.a",
        role: "TL",
        importance: "media",
      },
      {
        id: "peo-repite",
        q: "faq.q.peo-repite.q",
        a: "faq.q.peo-repite.a",
        role: "TL",
        importance: "media",
      },
    ],
  },
  {
    id: "security",
    title: "faq.cat.security.title",
    description: "faq.cat.security.desc",
    items: [
      {
        id: "sec-almacena",
        q: "faq.q.sec-almacena.q",
        a: "faq.q.sec-almacena.a",
        role: "Admin",
        importance: "alta",
        featured: ["seguridad"],
      },
      {
        id: "sec-no-almacena",
        q: "faq.q.sec-no-almacena.q",
        a: "faq.q.sec-no-almacena.a",
        role: "Admin",
        importance: "alta",
        featured: ["seguridad"],
      },
      {
        id: "sec-codigo",
        q: "faq.q.sec-codigo.q",
        a: "faq.q.sec-codigo.a",
        role: "Admin",
        importance: "alta",
        featured: ["seguridad"],
      },
      {
        id: "sec-conversaciones",
        q: "faq.q.sec-conversaciones.q",
        a: "faq.q.sec-conversaciones.a",
        role: "Admin",
        importance: "alta",
        featured: ["seguridad"],
      },
      {
        id: "sec-modifica",
        q: "faq.q.sec-modifica.q",
        a: "faq.q.sec-modifica.a",
        role: "Admin",
        importance: "alta",
        featured: ["seguridad"],
      },
      {
        id: "sec-permisos",
        q: "faq.q.sec-permisos.q",
        a: "faq.q.sec-permisos.a",
        role: "Admin",
        importance: "media",
      },
      {
        id: "sec-quien-ve",
        q: "faq.q.sec-quien-ve.q",
        a: "faq.q.sec-quien-ve.a",
        role: "Admin",
        importance: "media",
      },
      {
        id: "sec-limitar-rol",
        q: "faq.q.sec-limitar-rol.q",
        a: "faq.q.sec-limitar-rol.a",
        role: "Admin",
        importance: "media",
        featured: ["seguridad"],
      },
      {
        id: "sec-eliminar-integracion",
        q: "faq.q.sec-eliminar-integracion.q",
        a: "faq.q.sec-eliminar-integracion.a",
        role: "Admin",
        importance: "media",
      },
      {
        id: "sec-eliminar-workspace",
        q: "faq.q.sec-eliminar-workspace.q",
        a: "faq.q.sec-eliminar-workspace.a",
        role: "Admin",
        importance: "media",
      },
      {
        id: "sec-exportar",
        q: "faq.q.sec-exportar.q",
        a: "faq.q.sec-exportar.a",
        role: "Admin",
        importance: "media",
      },
      {
        id: "sec-borrar",
        q: "faq.q.sec-borrar.q",
        a: "faq.q.sec-borrar.a",
        role: "Admin",
        importance: "media",
      },
      {
        id: "sec-proteccion",
        q: "faq.q.sec-proteccion.q",
        a: "faq.q.sec-proteccion.a",
        role: "Admin",
        importance: "alta",
        featured: ["seguridad"],
      },
      {
        id: "sec-buenas-practicas",
        q: "faq.q.sec-buenas-practicas.q",
        a: "faq.q.sec-buenas-practicas.a",
        role: "Admin",
        importance: "media",
        featured: ["seguridad"],
      },
      {
        id: "sec-info-sensible",
        q: "faq.q.sec-info-sensible.q",
        a: "faq.q.sec-info-sensible.a",
        role: "Director",
        importance: "media",
      },
      {
        id: "sec-usuario-sale",
        q: "faq.q.sec-usuario-sale.q",
        a: "faq.q.sec-usuario-sale.a",
        role: "Admin",
        importance: "media",
      },
    ],
  },
  {
    id: "plans",
    title: "faq.cat.plans.title",
    description: "faq.cat.plans.desc",
    items: [
      {
        id: "pla-prueba",
        q: "faq.q.pla-prueba.q",
        a: "faq.q.pla-prueba.a",
        role: "Todos",
        importance: "alta",
        featured: ["nuevos"],
      },
      {
        id: "pla-incluye",
        q: "faq.q.pla-incluye.q",
        a: "faq.q.pla-incluye.a",
        role: "Admin",
        importance: "alta",
        featured: ["nuevos"],
      },
      {
        id: "pla-limites",
        q: "faq.q.pla-limites.q",
        a: "faq.q.pla-limites.a",
        role: "Admin",
        importance: "media",
      },
      {
        id: "pla-usuarios",
        q: "faq.q.pla-usuarios.q",
        a: "faq.q.pla-usuarios.a",
        role: "Admin",
        importance: "alta",
      },
      {
        id: "pla-proyectos",
        q: "faq.q.pla-proyectos.q",
        a: "faq.q.pla-proyectos.a",
        role: "Admin",
        importance: "media",
      },
      {
        id: "pla-integraciones",
        q: "faq.q.pla-integraciones.q",
        a: "faq.q.pla-integraciones.a",
        role: "Admin",
        importance: "media",
      },
      {
        id: "pla-reportes-mes",
        q: "faq.q.pla-reportes-mes.q",
        a: "faq.q.pla-reportes-mes.a",
        role: "Admin",
        importance: "baja",
      },
      {
        id: "pla-automaticos",
        q: "faq.q.pla-automaticos.q",
        a: "faq.q.pla-automaticos.a",
        role: "Admin",
        importance: "media",
      },
      {
        id: "pla-export",
        q: "faq.q.pla-export.q",
        a: "faq.q.pla-export.a",
        role: "Admin",
        importance: "baja",
      },
      {
        id: "pla-soporte",
        q: "faq.q.pla-soporte.q",
        a: "faq.q.pla-soporte.a",
        role: "Admin",
        importance: "baja",
      },
      {
        id: "pla-diferencia-planes",
        q: "faq.q.pla-diferencia-planes.q",
        a: "faq.q.pla-diferencia-planes.a",
        role: "Admin",
        importance: "media",
      },
      {
        id: "pla-anual",
        q: "faq.q.pla-anual.q",
        a: "faq.q.pla-anual.a",
        role: "Admin",
        importance: "media",
      },
      {
        id: "pla-cambiar",
        q: "faq.q.pla-cambiar.q",
        a: "faq.q.pla-cambiar.a",
        role: "Admin",
        importance: "media",
      },
      {
        id: "pla-cancelar",
        q: "faq.q.pla-cancelar.q",
        a: "faq.q.pla-cancelar.a",
        role: "Admin",
        importance: "media",
      },
      {
        id: "pla-datos-cancelar",
        q: "faq.q.pla-datos-cancelar.q",
        a: "faq.q.pla-datos-cancelar.a",
        role: "Admin",
        importance: "media",
      },
      {
        id: "pla-empresas",
        q: "faq.q.pla-empresas.q",
        a: "faq.q.pla-empresas.a",
        role: "Director",
        importance: "media",
      },
    ],
  },
  {
    id: "daily",
    title: "faq.cat.daily.title",
    description: "faq.cat.daily.desc",
    items: [
      {
        id: "day-cada-dia",
        q: "faq.q.day-cada-dia.q",
        a: "faq.q.day-cada-dia.a",
        role: "Todos",
        importance: "media",
      },
      {
        id: "day-daily",
        q: "faq.q.day-daily.q",
        a: "faq.q.day-daily.a",
        role: "TL",
        importance: "media",
      },
      {
        id: "day-planning",
        q: "faq.q.day-planning.q",
        a: "faq.q.day-planning.a",
        role: "PO",
        importance: "media",
      },
      {
        id: "day-retro",
        q: "faq.q.day-retro.q",
        a: "faq.q.day-retro.a",
        role: "TL",
        importance: "media",
      },
      {
        id: "day-demo",
        q: "faq.q.day-demo.q",
        a: "faq.q.day-demo.a",
        role: "PO",
        importance: "baja",
      },
      {
        id: "day-ejecutiva",
        q: "faq.q.day-ejecutiva.q",
        a: "faq.q.day-ejecutiva.a",
        role: "Director",
        importance: "media",
      },
      {
        id: "day-hoy",
        q: "faq.q.day-hoy.q",
        a: "faq.q.day-hoy.a",
        role: "Todos",
        importance: "media",
      },
      {
        id: "day-revisado",
        q: "faq.q.day-revisado.q",
        a: "faq.q.day-revisado.a",
        role: "Todos",
        importance: "baja",
      },
      {
        id: "day-accion",
        q: "faq.q.day-accion.q",
        a: "faq.q.day-accion.a",
        role: "Todos",
        importance: "baja",
      },
      {
        id: "day-insight",
        q: "faq.q.day-insight.q",
        a: "faq.q.day-insight.a",
        role: "Todos",
        importance: "baja",
      },
      {
        id: "day-tarea-alerta",
        q: "faq.q.day-tarea-alerta.q",
        a: "faq.q.day-tarea-alerta.a",
        role: "TL",
        importance: "baja",
      },
      {
        id: "day-decision",
        q: "faq.q.day-decision.q",
        a: "faq.q.day-decision.a",
        role: "Todos",
        importance: "baja",
      },
    ],
  },
  {
    id: "troubleshooting",
    title: "faq.cat.troubleshooting.title",
    description: "faq.cat.troubleshooting.desc",
    items: [
      {
        id: "tro-sin-datos",
        q: "faq.q.tro-sin-datos.q",
        a: "faq.q.tro-sin-datos.a",
        role: "Admin",
        importance: "media",
      },
      {
        id: "tro-metrica-cero",
        q: "faq.q.tro-metrica-cero.q",
        a: "faq.q.tro-metrica-cero.a",
        role: "Admin",
        importance: "media",
      },
      {
        id: "tro-sin-prs",
        q: "faq.q.tro-sin-prs.q",
        a: "faq.q.tro-sin-prs.a",
        role: "Admin",
        importance: "media",
      },
      {
        id: "tro-sin-jira",
        q: "faq.q.tro-sin-jira.q",
        a: "faq.q.tro-sin-jira.a",
        role: "Admin",
        importance: "media",
      },
      {
        id: "tro-sin-slack",
        q: "faq.q.tro-sin-slack.q",
        a: "faq.q.tro-sin-slack.a",
        role: "Admin",
        importance: "baja",
      },
      {
        id: "tro-falla-integracion",
        q: "faq.q.tro-falla-integracion.q",
        a: "faq.q.tro-falla-integracion.a",
        role: "Admin",
        importance: "media",
      },
      {
        id: "tro-tarda",
        q: "faq.q.tro-tarda.q",
        a: "faq.q.tro-tarda.a",
        role: "Admin",
        importance: "baja",
      },
      {
        id: "tro-incorrecto",
        q: "faq.q.tro-incorrecto.q",
        a: "faq.q.tro-incorrecto.a",
        role: "Admin",
        importance: "media",
      },
      {
        id: "tro-resync",
        q: "faq.q.tro-resync.q",
        a: "faq.q.tro-resync.a",
        role: "Admin",
        importance: "media",
      },
      {
        id: "tro-reportar",
        q: "faq.q.tro-reportar.q",
        a: "faq.q.tro-reportar.a",
        role: "Todos",
        importance: "media",
      },
      {
        id: "tro-soporte",
        q: "faq.q.tro-soporte.q",
        a: "faq.q.tro-soporte.a",
        role: "Todos",
        importance: "media",
      },
      {
        id: "tro-estado-integraciones",
        q: "faq.q.tro-estado-integraciones.q",
        a: "faq.q.tro-estado-integraciones.a",
        role: "Admin",
        importance: "media",
      },
      {
        id: "tro-datos-insuficientes",
        q: "faq.q.tro-datos-insuficientes.q",
        a: "faq.q.tro-datos-insuficientes.a",
        role: "Admin",
        importance: "media",
      },
      {
        id: "tro-generacion-fallida",
        q: "faq.q.tro-generacion-fallida.q",
        a: "faq.q.tro-generacion-fallida.a",
        role: "Admin",
        importance: "media",
      },
    ],
  },
  {
    id: "customization",
    title: "faq.cat.customization.title",
    description: "faq.cat.customization.desc",
    items: [
      {
        id: "cus-reportes",
        q: "faq.q.cus-reportes.q",
        a: "faq.q.cus-reportes.a",
        role: "Admin",
        importance: "media",
      },
      {
        id: "cus-metricas",
        q: "faq.q.cus-metricas.q",
        a: "faq.q.cus-metricas.a",
        role: "Admin",
        importance: "baja",
      },
      {
        id: "cus-alertas",
        q: "faq.q.cus-alertas.q",
        a: "faq.q.cus-alertas.a",
        role: "Admin",
        importance: "baja",
      },
      {
        id: "cus-kpis-rol",
        q: "faq.q.cus-kpis-rol.q",
        a: "faq.q.cus-kpis-rol.a",
        role: "Todos",
        importance: "media",
      },
      {
        id: "cus-vistas",
        q: "faq.q.cus-vistas.q",
        a: "faq.q.cus-vistas.a",
        role: "Admin",
        importance: "baja",
      },
      {
        id: "cus-plantillas",
        q: "faq.q.cus-plantillas.q",
        a: "faq.q.cus-plantillas.a",
        role: "Admin",
        importance: "baja",
      },
      {
        id: "cus-recurrentes",
        q: "faq.q.cus-recurrentes.q",
        a: "faq.q.cus-recurrentes.a",
        role: "Admin",
        importance: "media",
      },
      {
        id: "cus-permisos",
        q: "faq.q.cus-permisos.q",
        a: "faq.q.cus-permisos.a",
        role: "Admin",
        importance: "media",
      },
      {
        id: "cus-idioma",
        q: "faq.q.cus-idioma.q",
        a: "faq.q.cus-idioma.a",
        role: "Todos",
        importance: "baja",
      },
      {
        id: "cus-ocultar",
        q: "faq.q.cus-ocultar.q",
        a: "faq.q.cus-ocultar.a",
        role: "Admin",
        importance: "media",
      },
      {
        id: "cus-score-propio",
        q: "faq.q.cus-score-propio.q",
        a: "faq.q.cus-score-propio.a",
        role: "Admin",
        importance: "baja",
      },
      {
        id: "cus-tags",
        q: "faq.q.cus-tags.q",
        a: "faq.q.cus-tags.a",
        role: "Admin",
        importance: "baja",
      },
    ],
  },
  {
    id: "ai",
    title: "faq.cat.ai.title",
    description: "faq.cat.ai.desc",
    items: [
      {
        id: "ai-como-usa",
        q: "faq.q.ai-como-usa.q",
        a: "faq.q.ai-como-usa.a",
        role: "Director",
        importance: "media",
      },
      {
        id: "ai-que-analiza",
        q: "faq.q.ai-que-analiza.q",
        a: "faq.q.ai-que-analiza.a",
        role: "Todos",
        importance: "alta",
      },
      {
        id: "ai-decisiones",
        q: "faq.q.ai-decisiones.q",
        a: "faq.q.ai-decisiones.a",
        role: "Todos",
        importance: "alta",
      },
      {
        id: "ai-reemplaza",
        q: "faq.q.ai-reemplaza.q",
        a: "faq.q.ai-reemplaza.a",
        role: "Todos",
        importance: "media",
      },
      {
        id: "ai-insights",
        q: "faq.q.ai-insights.q",
        a: "faq.q.ai-insights.a",
        role: "Todos",
        importance: "media",
      },
      {
        id: "ai-recomendaciones",
        q: "faq.q.ai-recomendaciones.q",
        a: "faq.q.ai-recomendaciones.a",
        role: "Todos",
        importance: "media",
      },
      {
        id: "ai-patrones",
        q: "faq.q.ai-patrones.q",
        a: "faq.q.ai-patrones.a",
        role: "TL",
        importance: "baja",
      },
      {
        id: "ai-injustas",
        q: "faq.q.ai-injustas.q",
        a: "faq.q.ai-injustas.a",
        role: "TL",
        importance: "alta",
        featured: ["TL"],
      },
      {
        id: "ai-editar",
        q: "faq.q.ai-editar.q",
        a: "faq.q.ai-editar.a",
        role: "Todos",
        importance: "media",
      },
      {
        id: "ai-regenerar",
        q: "faq.q.ai-regenerar.q",
        a: "faq.q.ai-regenerar.a",
        role: "Todos",
        importance: "baja",
      },
      {
        id: "ai-fuentes",
        q: "faq.q.ai-fuentes.q",
        a: "faq.q.ai-fuentes.a",
        role: "Todos",
        importance: "media",
      },
      {
        id: "ai-equivoca",
        q: "faq.q.ai-equivoca.q",
        a: "faq.q.ai-equivoca.a",
        role: "Todos",
        importance: "alta",
      },
      {
        id: "ai-validar",
        q: "faq.q.ai-validar.q",
        a: "faq.q.ai-validar.a",
        role: "Todos",
        importance: "media",
      },
    ],
  },
  {
    id: "commercial",
    title: "faq.cat.commercial.title",
    description: "faq.cat.commercial.desc",
    items: [
      {
        id: "com-ya-jira",
        q: "faq.q.com-ya-jira.q",
        a: "faq.q.com-ya-jira.a",
        role: "Todos",
        importance: "alta",
        featured: ["nuevos"],
      },
      {
        id: "com-ya-dashboards",
        q: "faq.q.com-ya-dashboards.q",
        a: "faq.q.com-ya-dashboards.a",
        role: "Todos",
        importance: "media",
      },
      {
        id: "com-vs-bi",
        q: "faq.q.com-vs-bi.q",
        a: "faq.q.com-vs-bi.a",
        role: "Director",
        importance: "media",
      },
      {
        id: "com-vs-manual",
        q: "faq.q.com-vs-manual.q",
        a: "faq.q.com-vs-manual.a",
        role: "Todos",
        importance: "media",
      },
      {
        id: "com-ahorro",
        q: "faq.q.com-ahorro.q",
        a: "faq.q.com-ahorro.a",
        role: "Todos",
        importance: "media",
      },
      {
        id: "com-previsibilidad",
        q: "faq.q.com-previsibilidad.q",
        a: "faq.q.com-previsibilidad.a",
        role: "Director",
        importance: "media",
      },
      {
        id: "com-riesgos",
        q: "faq.q.com-riesgos.q",
        a: "faq.q.com-riesgos.a",
        role: "Director",
        importance: "media",
      },
      {
        id: "com-tl",
        q: "faq.q.com-tl.q",
        a: "faq.q.com-tl.a",
        role: "TL",
        importance: "media",
      },
      {
        id: "com-po",
        q: "faq.q.com-po.q",
        a: "faq.q.com-po.a",
        role: "PO",
        importance: "media",
      },
      {
        id: "com-gerentes",
        q: "faq.q.com-gerentes.q",
        a: "faq.q.com-gerentes.a",
        role: "Director",
        importance: "media",
      },
      {
        id: "com-convencer-equipo",
        q: "faq.q.com-convencer-equipo.q",
        a: "faq.q.com-convencer-equipo.a",
        role: "Todos",
        importance: "media",
      },
      {
        id: "com-presentar-direccion",
        q: "faq.q.com-presentar-direccion.q",
        a: "faq.q.com-presentar-direccion.a",
        role: "Director",
        importance: "media",
        featured: ["Director"],
      },
      {
        id: "com-roi",
        q: "faq.q.com-roi.q",
        a: "faq.q.com-roi.a",
        role: "Director",
        importance: "media",
      },
      {
        id: "com-tiempo-valor",
        q: "faq.q.com-tiempo-valor.q",
        a: "faq.q.com-tiempo-valor.a",
        role: "Todos",
        importance: "media",
        featured: ["nuevos"],
      },
    ],
  },
];

export const FEATURED_GROUPS: { id: FeaturedGroup; title: string; description: string }[] = [
  {
    id: "nuevos",
    title: "faq.featured.nuevos.title",
    description: "faq.featured.nuevos.desc",
  },
  {
    id: "TL",
    title: "faq.featured.TL.title",
    description: "faq.featured.TL.desc",
  },
  {
    id: "PO",
    title: "faq.featured.PO.title",
    description: "faq.featured.PO.desc",
  },
  {
    id: "Director",
    title: "faq.featured.Director.title",
    description: "faq.featured.Director.desc",
  },
  {
    id: "seguridad",
    title: "faq.featured.seguridad.title",
    description: "faq.featured.seguridad.desc",
  },
];

// Índice plano de todos los items, útil para búsqueda y destacadas.
export interface FaqIndexItem extends FaqItem {
  categoryId: string;
  categoryTitle: string;
}

export const FAQ_INDEX: FaqIndexItem[] = FAQ.flatMap((cat) =>
  cat.items.map((item) => ({
    ...item,
    categoryId: cat.id,
    categoryTitle: cat.title,
  })),
);
