// Centro de Ayuda / FAQ de DevMetrics.
// Base de conocimiento estructurada: categorías -> preguntas/respuestas.
// Cada item declara el rol más interesado y su nivel de importancia.

export type HelpRole = "Todos" | "TL" | "PO" | "Director" | "Admin";
export type HelpImportance = "alta" | "media" | "baja";
export type FeaturedGroup = "nuevos" | "TL" | "PO" | "Director" | "seguridad";

export interface FaqItem {
  id: string;
  q: string;
  a: string;
  role: HelpRole;
  importance: HelpImportance;
  featured?: FeaturedGroup[];
}

export interface FaqCategory {
  id: string;
  title: string;
  description: string;
  items: FaqItem[];
}

export const IMPORTANCE_LABEL: Record<HelpImportance, string> = {
  alta: "Alta",
  media: "Media",
  baja: "Baja",
};

export const ROLE_FILTERS: HelpRole[] = [
  "Todos",
  "TL",
  "PO",
  "Director",
  "Admin",
];

// Microcopy sugerido para el buscador del Centro de Ayuda.
export const SEARCH_PLACEHOLDER = "Buscá por tema, métrica o pregunta…";
export const SEARCH_SUBTEXT =
  "Probá con “conectar Jira”, “qué es velocity”, “reporte en riesgo” o “cambiar de plan”.";
export const SEARCH_EMPTY =
  "No encontramos una respuesta para eso. Reformulá la búsqueda o escribinos desde Contacto y te ayudamos.";

export const FAQ_INTRO =
  "Todo lo que necesitás para sacarle provecho a DevMetrics: qué es, cómo conectás tus herramientas, cómo se leen los reportes y las métricas, y cómo cuidamos tus datos. Usá el buscador o filtrá por tu rol para ir directo a lo tuyo.";

export const FAQ: FaqCategory[] = [
  {
    id: "general",
    title: "Sobre DevMetrics",
    description:
      "Qué es, para qué sirve y en qué se diferencia de las herramientas que ya usás.",
    items: [
      {
        id: "gen-que-es",
        q: "¿Qué es DevMetrics?",
        a: "DevMetrics es una plataforma SaaS que conecta tus herramientas de desarrollo (Jira, GitHub, GitLab, Slack y más) y genera reportes automáticos sobre el estado real de tus sprints, proyectos y equipos: avance, calidad, riesgos y personas, todo en un solo lugar.",
        role: "Todos",
        importance: "alta",
        featured: ["nuevos"],
      },
      {
        id: "gen-para-que",
        q: "¿Para qué sirve?",
        a: "Para entender el estado de un proyecto sin armar reportes a mano. Cruza datos de varias fuentes y te muestra qué avanzó, qué está trabado, dónde hay riesgo y qué conviene decidir esta semana.",
        role: "Todos",
        importance: "alta",
        featured: ["nuevos"],
      },
      {
        id: "gen-a-quien",
        q: "¿A quién está dirigida?",
        a: "A Tech Leads, Product Owners, Scrum Masters, líderes de equipo, gerentes y directores de tecnología que necesitan visibilidad clara del estado de uno o varios equipos, con lecturas adaptadas a cada rol.",
        role: "Todos",
        importance: "alta",
      },
      {
        id: "gen-problema",
        q: "¿Qué problema resuelve?",
        a: "Elimina el trabajo manual de juntar datos dispersos en Jira, Git y chats para saber cómo viene un sprint. En vez de intuición o planillas, tenés una lectura objetiva y comparable período a período.",
        role: "Todos",
        importance: "alta",
      },
      {
        id: "gen-vs-jira",
        q: "¿En qué se diferencia de Jira, GitHub, GitLab o Slack?",
        a: "Esas herramientas guardan los datos; DevMetrics los interpreta. En lugar de mirar cinco tableros por separado, cruzamos todo en un reporte con salud, riesgos y recomendaciones. No reemplazamos tus herramientas: las leemos.",
        role: "Todos",
        importance: "alta",
        featured: ["nuevos"],
      },
      {
        id: "gen-vs-dashboards",
        q: "¿En qué se diferencia de un dashboard tradicional?",
        a: "Un dashboard muestra números; DevMetrics los explica. Además de graficar métricas, detecta patrones, señala qué mirar primero y sugiere acciones según el rol. No tenés que interpretar los gráficos vos solo.",
        role: "Todos",
        importance: "media",
      },
      {
        id: "gen-tipos-equipo",
        q: "¿Qué tipo de equipos pueden usarla?",
        a: "Desde una sola squad hasta decenas de equipos en paralelo. Funciona igual de bien para producto interno, factories, consultoras y áreas de tecnología que necesitan reportar hacia arriba.",
        role: "Todos",
        importance: "media",
      },
      {
        id: "gen-agiles",
        q: "¿Sirve para equipos ágiles?",
        a: "Sí. Está pensada alrededor del ciclo de sprint: completion rate, velocity, scope creep, tareas arrastradas y comparación entre sprints. Se integra naturalmente a daily, planning y retro.",
        role: "Todos",
        importance: "media",
      },
      {
        id: "gen-remoto",
        q: "¿Sirve para equipos remotos o híbridos?",
        a: "Especialmente. Al centralizar el estado en reportes compartibles, reduce la dependencia de reuniones para saber cómo viene todo. Cada quien ve lo mismo, sin importar dónde esté.",
        role: "Todos",
        importance: "baja",
      },
      {
        id: "gen-startups",
        q: "¿Sirve para startups, software factories, consultoras o áreas internas?",
        a: "Sí. Startups la usan para previsibilidad, las factories y consultoras para reportar a clientes, y las áreas internas para dar visibilidad a dirección. El multi-proyecto (plan Pro) está pensado justo para esos casos.",
        role: "Director",
        importance: "media",
      },
      {
        id: "gen-tiempo-ahorro",
        q: "¿Cuánto tiempo ahorra?",
        a: "Reemplaza las horas semanales que se van en armar reportes de estado a mano. El tiempo real depende de cuántas fuentes conectes, pero el reporte se genera en segundos en lugar de horas.",
        role: "Todos",
        importance: "media",
      },
      {
        id: "gen-valor-primer-uso",
        q: "¿Qué valor entrega desde el primer uso?",
        a: "Con solo conectar Jira o GitHub y generar un reporte, ya ves avance, PRs, bloqueos y un score de salud. El valor crece a medida que sumás fuentes e historial para comparar.",
        role: "Todos",
        importance: "alta",
        featured: ["nuevos"],
      },
      {
        id: "gen-decisiones",
        q: "¿Qué decisiones ayuda a tomar?",
        a: "Repriorizar el sprint, desbloquear a tiempo, redistribuir carga, acompañar a alguien del equipo, escalar un riesgo a dirección o decidir si un proyecto necesita atención. Siempre con datos que respaldan la conversación.",
        role: "Todos",
        importance: "media",
      },
    ],
  },
  {
    id: "setup",
    title: "Configuración inicial",
    description: "Cómo arrancar: cuenta, workspace, proyecto e integraciones.",
    items: [
      {
        id: "set-cuenta",
        q: "¿Cómo creo una cuenta?",
        a: "Registrate con tu email desde “Empezar gratis”. En minutos tenés un workspace listo. No hace falta tarjeta para el plan Free.",
        role: "Todos",
        importance: "alta",
        featured: ["nuevos"],
      },
      {
        id: "set-invitar",
        q: "¿Cómo invito a mi equipo?",
        a: "Desde Equipos podés invitar miembros por email y asignarles un rol. La cantidad de usuarios depende de tu plan (Free 5, Team 45, Pro ilimitados).",
        role: "Admin",
        importance: "media",
      },
      {
        id: "set-workspace",
        q: "¿Cómo creo un workspace?",
        a: "Se crea automáticamente al registrarte. Un workspace agrupa tus proyectos, integraciones, equipo y reportes; es tu espacio de trabajo principal.",
        role: "Admin",
        importance: "media",
      },
      {
        id: "set-proyecto",
        q: "¿Cómo creo un proyecto?",
        a: "Desde Proyectos > Nuevo proyecto. Cada proyecto tiene sus propias integraciones y reportes. El multi-proyecto está disponible en el plan Pro.",
        role: "Admin",
        importance: "alta",
      },
      {
        id: "set-conectar",
        q: "¿Cómo conecto mis herramientas?",
        a: "Desde Integraciones elegís la herramienta y seguís el asistente paso a paso. Cada integración te indica exactamente qué necesita (token, permisos) y links a la guía oficial.",
        role: "Admin",
        importance: "alta",
        featured: ["nuevos"],
      },
      {
        id: "set-permisos",
        q: "¿Qué permisos necesita cada integración?",
        a: "Siempre pedimos el mínimo posible y de solo lectura. Por ejemplo, en Jira alcanza con leer issues y sprints; en GitHub, leer repos y PRs. El asistente detalla los scopes antes de conectar.",
        role: "Admin",
        importance: "alta",
        featured: ["seguridad"],
      },
      {
        id: "set-tiempo",
        q: "¿Cuánto tarda la configuración inicial?",
        a: "Conectar la primera herramienta y generar tu primer reporte lleva unos pocos minutos. Sumar más fuentes es igual de rápido y podés hacerlo cuando quieras.",
        role: "Admin",
        importance: "media",
      },
      {
        id: "set-ayuda-tecnica",
        q: "¿Necesito ayuda técnica para configurarla?",
        a: "No. El asistente está pensado para roles no técnicos e incluye enlaces a las guías oficiales de cada herramienta. Si te trabás, soporte te acompaña.",
        role: "Todos",
        importance: "media",
      },
      {
        id: "set-sin-todas",
        q: "¿Qué pasa si no conecto todas las herramientas?",
        a: "Funciona igual: los reportes muestran lo que sí tenés conectado y avisan qué métricas requieren otra fuente. Cuantas más conectes, más completo es el cruce por equipo y persona.",
        role: "Todos",
        importance: "alta",
      },
      {
        id: "set-manual",
        q: "¿Puedo usarla con datos cargados manualmente?",
        a: "DevMetrics está diseñada para conectarse en vivo a tus herramientas, que es donde ya vive tu información. Hoy no reemplaza esas fuentes con carga manual; la fortaleza es la sincronización automática.",
        role: "Todos",
        importance: "baja",
      },
      {
        id: "set-historicos",
        q: "¿Puedo importar reportes históricos?",
        a: "Al conectar una herramienta leemos el historial disponible en ella (sprints y actividad pasada), así podés comparar períodos desde temprano. La profundidad depende de lo que exponga cada API.",
        role: "Todos",
        importance: "media",
      },
      {
        id: "set-solo-jira",
        q: "¿Puedo empezar solo con Jira o solo con GitHub?",
        a: "Sí, y es lo más recomendado para arrancar. El plan Free incluye Jira + GitHub en vivo. Después sumás fuentes según lo que quieras medir.",
        role: "Todos",
        importance: "alta",
        featured: ["nuevos"],
      },
    ],
  },
  {
    id: "integrations",
    title: "Integraciones",
    description:
      "Qué se conecta, qué datos leemos y cómo se mantienen sincronizados.",
    items: [
      {
        id: "int-cuales",
        q: "¿Qué herramientas puedo conectar?",
        a: "Gestión de tareas (Jira, Linear, ClickUp, Azure DevOps), código (GitHub, GitLab, Bitbucket), documentación/datos (Notion, Airtable) y comunicación (Slack, Teams, Discord). La disponibilidad depende del plan.",
        role: "Admin",
        importance: "alta",
      },
      {
        id: "int-jira",
        q: "¿Cómo conecto Jira?",
        a: "En Integraciones > Jira ingresás la URL de tu instancia y un API token. El asistente enlaza a la guía oficial de Atlassian para generarlo. Leemos issues, sprints y estados; nunca modificamos nada.",
        role: "Admin",
        importance: "alta",
      },
      {
        id: "int-github",
        q: "¿Cómo conecto GitHub?",
        a: "Generás un token de acceso con permiso de lectura sobre los repos que quieras seguir y lo pegás en el asistente. Leemos PRs, commits y actividad de código.",
        role: "Admin",
        importance: "alta",
      },
      {
        id: "int-gitlab",
        q: "¿Cómo conecto GitLab?",
        a: "Con un Personal Access Token de solo lectura. Podés apuntar a un grupo o a proyectos específicos. Leemos merge requests, commits y pipelines.",
        role: "Admin",
        importance: "media",
      },
      {
        id: "int-bitbucket",
        q: "¿Cómo conecto Bitbucket?",
        a: "Con un app password de solo lectura sobre repos y pull requests. El asistente te guía paso a paso para generarlo.",
        role: "Admin",
        importance: "media",
      },
      {
        id: "int-slack",
        q: "¿Cómo conecto Slack?",
        a: "Autorizás la app y elegís los canales a seguir. Usamos señales de actividad y comunicación de bloqueos, no el contenido privado de las conversaciones. Disponible en plan Pro.",
        role: "Admin",
        importance: "media",
      },
      {
        id: "int-teams",
        q: "¿Cómo conecto Microsoft Teams?",
        a: "Autorizás la integración y seleccionás los canales relevantes. Igual que con Slack, leemos señales de actividad, no mensajes privados. Disponible en plan Pro.",
        role: "Admin",
        importance: "media",
      },
      {
        id: "int-figma",
        q: "¿Cómo conecto Figma u otras herramientas de diseño?",
        a: "Estamos ampliando el catálogo de integraciones. Si Figma u otra herramienta que usás todavía no aparece, escribinos desde Contacto para priorizarla en el roadmap.",
        role: "Admin",
        importance: "baja",
      },
      {
        id: "int-qa-cicd",
        q: "¿Puedo conectar herramientas de QA, CI/CD o documentación?",
        a: "Leemos señales de CI/CD desde las plataformas de código que ya lo exponen (builds y pipelines de GitHub/GitLab). Integraciones dedicadas de cobertura, calidad e incidentes (Codecov, SonarQube, PagerDuty) están en el roadmap.",
        role: "TL",
        importance: "media",
      },
      {
        id: "int-que-datos",
        q: "¿Qué datos toma de cada herramienta?",
        a: "De tareas: estados, sprints, asignaciones y bloqueos. De código: PRs, commits, tiempos de review y CI. De comunicación: señales de actividad. Solo lo necesario para construir el reporte.",
        role: "Admin",
        importance: "alta",
        featured: ["seguridad"],
      },
      {
        id: "int-modifica",
        q: "¿DevMetrics modifica datos en las herramientas conectadas?",
        a: "No. Todas las integraciones son de solo lectura. No creamos, editamos ni borramos nada en Jira, GitHub, Slack ni en ninguna otra fuente.",
        role: "Admin",
        importance: "alta",
        featured: ["seguridad"],
      },
      {
        id: "int-lee-escribe",
        q: "¿La app solo lee información o también escribe?",
        a: "Solo lee. Escribir de vuelta (por ejemplo, crear una tarea en Jira desde una alerta) es una funcionalidad opcional del roadmap y siempre requeriría tu confirmación explícita.",
        role: "Admin",
        importance: "media",
        featured: ["seguridad"],
      },
      {
        id: "int-desconecta",
        q: "¿Qué pasa si una integración se desconecta?",
        a: "El reporte sigue funcionando con las fuentes activas y marcamos la integración como desconectada. Suele deberse a un token vencido o revocado; volver a conectarla toma un minuto.",
        role: "Admin",
        importance: "media",
      },
      {
        id: "int-resync",
        q: "¿Cómo reintento una sincronización?",
        a: "Desde Integraciones podés probar la conexión y forzar una resincronización. Si falla, te mostramos el motivo (token, permisos o límite de la API) para resolverlo.",
        role: "Admin",
        importance: "media",
      },
      {
        id: "int-frecuencia",
        q: "¿Cada cuánto se actualizan los datos?",
        a: "Los datos se leen al generar o programar un reporte, así reflejan el estado del momento. También podés resincronizar manualmente cuando quieras el dato más fresco.",
        role: "Admin",
        importance: "media",
      },
      {
        id: "int-elegir-scope",
        q: "¿Puedo elegir qué repos, proyectos o canales conectar?",
        a: "Sí. En cada integración seleccionás el alcance exacto: qué repos, qué proyectos de Jira o qué canales seguir. Nada se lee por fuera de lo que elegís.",
        role: "Admin",
        importance: "media",
        featured: ["seguridad"],
      },
      {
        id: "int-acceso-equipo",
        q: "¿Cómo limito el acceso por equipo o proyecto?",
        a: "Las integraciones viven a nivel de proyecto y los reportes se comparten según rol y membresía. Cada persona ve solo los proyectos de los que forma parte.",
        role: "Admin",
        importance: "media",
      },
    ],
  },
  {
    id: "reports",
    title: "Reportes",
    description: "Cómo se generan, qué significan los estados y cómo se leen.",
    items: [
      {
        id: "rep-tipos",
        q: "¿Qué tipos de reportes genera?",
        a: "Un reporte central por período con lecturas por rol: la vista de sprint (operativa), la ejecutiva (resumen de salud y riesgos) y la técnica (código, PRs, CI). Además, comparativas entre períodos.",
        role: "Todos",
        importance: "alta",
        featured: ["nuevos"],
      },
      {
        id: "rep-generar",
        q: "¿Cómo genero un reporte?",
        a: "Desde Reportes > Generar reporte. Elegís el período y DevMetrics cruza tus fuentes conectadas en segundos. Podés fijarlo, etiquetarlo y compartirlo.",
        role: "Todos",
        importance: "alta",
        featured: ["nuevos"],
      },
      {
        id: "rep-diferencia-vistas",
        q: "¿Qué diferencia hay entre reporte de sprint, ejecutivo y técnico?",
        a: "Es el mismo reporte leído según quién mira: el de sprint se enfoca en avance y bloqueos (TL/Scrum), el ejecutivo en salud, riesgos y tendencia (Dirección), y el técnico en PRs, review y CI (TL/devs).",
        role: "Todos",
        importance: "alta",
      },
      {
        id: "rep-saludable",
        q: "¿Qué significa un reporte “saludable”?",
        a: "Que el score de salud es alto: el avance, la calidad y el ritmo están dentro de lo esperado y no hay riesgos relevantes. Igual conviene una lectura rápida por si hay algo que sostener.",
        role: "Todos",
        importance: "media",
      },
      {
        id: "rep-alto-riesgo",
        q: "¿Qué significa un reporte de “alto riesgo”?",
        a: "Que hay señales que probablemente impacten la entrega: mucho trabajo trabado, scope creciente o caída de ritmo. Es prioridad de revisión y suele requerir una decisión esta semana.",
        role: "Todos",
        importance: "alta",
      },
      {
        id: "rep-pendiente",
        q: "¿Qué significa un reporte “pendiente de revisión”?",
        a: "Que se generó pero todavía nadie lo marcó como revisado. Es una forma de saber qué reportes ya pasaron por el ojo de un responsable y cuáles no.",
        role: "Todos",
        importance: "baja",
      },
      {
        id: "rep-critico",
        q: "¿Qué significa un reporte “crítico”?",
        a: "Es el nivel más severo de salud: varias señales negativas a la vez que ponen en juego la entrega. Requiere atención inmediata y, muy probablemente, escalar a dirección.",
        role: "Todos",
        importance: "alta",
      },
      {
        id: "rep-interpretar",
        q: "¿Cómo interpreto un reporte?",
        a: "Empezá por el score de salud y las alertas destacadas; te dicen qué mirar primero. Después bajás a las métricas que expliquen esa señal y a las recomendaciones sugeridas para tu rol.",
        role: "Todos",
        importance: "alta",
        featured: ["nuevos"],
      },
      {
        id: "rep-compartir",
        q: "¿Cómo comparto un reporte?",
        a: "Cada reporte tiene opción de compartir con miembros del workspace y de enviarlo por email. Los stakeholders ven la lectura que les corresponde según su rol.",
        role: "Todos",
        importance: "media",
      },
      {
        id: "rep-exportar",
        q: "¿Puedo exportar a PDF o CSV?",
        a: "Sí. Podés exportar a CSV para análisis propio y enviar el reporte por email. La exportación está disponible desde el plan Free (CSV) y se amplía en los planes pagos.",
        role: "Todos",
        importance: "media",
      },
      {
        id: "rep-programar",
        q: "¿Puedo programar reportes automáticos?",
        a: "Sí, en los planes Team y Pro. Configurás la frecuencia (por ejemplo, cada fin de sprint) y DevMetrics genera y envía el reporte solo.",
        role: "Admin",
        importance: "media",
      },
      {
        id: "rep-comparar",
        q: "¿Puedo comparar dos sprints?",
        a: "Sí. La comparación muestra qué mejoró y qué empeoró entre dos períodos, con clasificación de tendencias y alertas de deterioro. Ideal para retros y seguimiento.",
        role: "Todos",
        importance: "alta",
        featured: ["TL", "Director"],
      },
      {
        id: "rep-tendencias",
        q: "¿Puedo ver tendencias mensuales?",
        a: "Sí. Hay atajos por último sprint, último mes, 3 meses, 6 meses y año para ver la evolución de las métricas clave en el tiempo.",
        role: "Director",
        importance: "media",
      },
      {
        id: "rep-por-entidad",
        q: "¿Puedo generar reportes por persona, equipo, sprint, proyecto o cliente?",
        a: "El reporte se genera por proyecto y período, e incluye desgloses por persona y equipo. Para clientes, cada proyecto puede representar una cuenta. El multi-proyecto está en el plan Pro.",
        role: "Todos",
        importance: "media",
      },
      {
        id: "rep-cual-primero",
        q: "¿Cómo sé qué reporte revisar primero?",
        a: "Ordenalos por score de salud: crítico y alto riesgo van primero. La sección ejecutiva ya resalta los proyectos que necesitan atención para que no tengas que buscarlos.",
        role: "Director",
        importance: "media",
        featured: ["Director"],
      },
      {
        id: "rep-incompletos",
        q: "¿Qué hago cuando un reporte muestra datos incompletos?",
        a: "Revisá qué fuentes están conectadas: si falta una métrica, casi siempre es porque su herramienta no está vinculada o se desconectó. El reporte te indica qué integración habilita cada dato.",
        role: "Admin",
        importance: "media",
      },
      {
        id: "rep-falla",
        q: "¿Qué hago cuando falla la generación de un reporte?",
        a: "Reintentá desde el mismo botón; si persiste, suele ser una integración con token vencido o un límite de API. Verificá el estado en Integraciones y, si sigue, escribinos a soporte.",
        role: "Admin",
        importance: "media",
      },
    ],
  },
  {
    id: "metrics",
    title: "Métricas",
    description:
      "Qué significa cada métrica, por qué importa, qué rol debería mirarla y qué hacer.",
    items: [
      {
        id: "met-completion",
        q: "Completion rate",
        a: "Qué es: porcentaje de lo planificado que se terminó en el sprint. Importa porque mide cumplimiento del compromiso. Si baja, hubo sobrecompromiso o bloqueos; si sube sostenido, el equipo estima bien. Rol: PO/Scrum. Acción: revisar planning y capacidad.",
        role: "PO",
        importance: "alta",
      },
      {
        id: "met-velocity",
        q: "Velocity",
        a: "Qué es: trabajo completado por sprint (puntos o tareas). Importa para proyectar entregas. Si cae, puede haber menos capacidad o más impedimentos; si sube errático, cuidado con la calidad. Rol: TL/PO. Acción: usarla para planificar, no para presionar.",
        role: "PO",
        importance: "alta",
      },
      {
        id: "met-throughput",
        q: "Throughput",
        a: "Qué es: cantidad de ítems finalizados en un período. Importa como medida simple de flujo. Si baja, el flujo se está frenando; si sube, mejoró la salida. Rol: TL/Scrum. Acción: cruzar con WIP y bloqueos para entender la causa.",
        role: "TL",
        importance: "media",
      },
      {
        id: "met-lead-time",
        q: "Lead time",
        a: "Qué es: tiempo desde que una tarea se crea hasta que se entrega. Importa para previsibilidad hacia el cliente. Si sube, hay demoras acumuladas; si baja, mejora la respuesta. Rol: PO/Director. Acción: mirar dónde se estanca (backlog o desarrollo).",
        role: "PO",
        importance: "media",
      },
      {
        id: "met-cycle-time",
        q: "Cycle time",
        a: "Qué es: tiempo desde que se empieza a trabajar una tarea hasta que se cierra. Importa para eficiencia del equipo. Si sube, hay fricción (review, retrabajo); si baja, el flujo es más ágil. Rol: TL. Acción: revisar tiempos de review y WIP.",
        role: "TL",
        importance: "media",
      },
      {
        id: "met-wip",
        q: "Work in progress (WIP)",
        a: "Qué es: cantidad de tareas abiertas en paralelo. Importa porque demasiado WIP frena todo. Si sube, hay dispersión; si baja, más foco. Rol: TL/Scrum. Acción: limitar WIP y cerrar antes de empezar más.",
        role: "TL",
        importance: "media",
      },
      {
        id: "met-scope-creep",
        q: "Scope creep",
        a: "Qué es: trabajo agregado después de iniciado el sprint. Importa porque erosiona el compromiso. Si sube, el alcance no está protegido; si baja, hay mejor refinamiento. Rol: PO. Acción: revisar entrada de trabajo y refinamiento.",
        role: "PO",
        importance: "alta",
        featured: ["PO"],
      },
      {
        id: "met-bloqueadas",
        q: "Tareas bloqueadas",
        a: "Qué es: ítems detenidos por una dependencia o impedimento. Importan porque son riesgo directo de entrega. Si suben, hay que desbloquear ya; si bajan, mejora el flujo. Rol: TL/Scrum. Acción: atacar bloqueos en la daily.",
        role: "TL",
        importance: "alta",
        featured: ["TL"],
      },
      {
        id: "met-arrastradas",
        q: "Tareas arrastradas (carry over)",
        a: "Qué es: tareas que pasan de un sprint al siguiente sin terminarse. Importan como señal de sobrecompromiso o bloqueos. Si suben, revisar tamaño de historias; si bajan, mejor planificación. Rol: PO/Scrum. Acción: ajustar el planning.",
        role: "PO",
        importance: "media",
      },
      {
        id: "met-bugs",
        q: "Bugs",
        a: "Qué es: defectos reportados y su evolución. Importan para calidad. Si suben, revisar testing y presión de entrega; si bajan, mejora la calidad. Rol: TL. Acción: balancear features vs. estabilidad.",
        role: "TL",
        importance: "media",
      },
      {
        id: "met-prs-abiertos",
        q: "PRs abiertos",
        a: "Qué es: pull/merge requests sin cerrar. Importan porque PRs estancados frenan la entrega. Si suben, hay cuello de botella en review; si bajan, buen flujo. Rol: TL. Acción: revisar carga de review.",
        role: "TL",
        importance: "media",
      },
      {
        id: "met-prs-merge",
        q: "PRs mergeados",
        a: "Qué es: cantidad de PRs integrados en el período. Importan como salida real de código. Si bajan, puede haber bloqueos o menos capacidad; si suben, buen ritmo. Rol: TL. Acción: cruzar con calidad para no premiar volumen a secas.",
        role: "TL",
        importance: "baja",
      },
      {
        id: "met-review-time",
        q: "Tiempo de review",
        a: "Qué es: cuánto tarda un PR desde que se abre hasta que se aprueba. Importa porque es un cuello de botella típico. Si sube, faltan reviewers o hay PRs muy grandes; si baja, mejora la velocidad. Rol: TL. Acción: repartir reviews y achicar PRs.",
        role: "TL",
        importance: "alta",
        featured: ["TL"],
      },
      {
        id: "met-coverage",
        q: "Test coverage",
        a: "Qué es: porcentaje de código cubierto por tests. Importa para riesgo de regresiones. Requiere conectar una herramienta de cobertura (Codecov/Sonar), integración en roadmap. Rol: TL. Acción: fijar un umbral mínimo por repo.",
        role: "TL",
        importance: "media",
      },
      {
        id: "met-build-failures",
        q: "Build failures",
        a: "Qué es: builds de CI que fallan. Importan porque frenan la integración. Si suben, hay inestabilidad en main o tests frágiles; si bajan, pipeline sano. Rol: TL. Acción: priorizar arreglar el build por sobre features.",
        role: "TL",
        importance: "media",
      },
      {
        id: "met-deploy-failures",
        q: "Deploy failures",
        a: "Qué es: despliegues fallidos. Importan por su impacto en producción y confianza. Si suben, revisar proceso de release; si bajan, deploy confiable. Rol: TL/Director. Acción: reforzar automatización y rollback.",
        role: "TL",
        importance: "media",
      },
      {
        id: "met-incidentes",
        q: "Incidentes",
        a: "Qué es: fallas en producción y su frecuencia. Importan para estabilidad del servicio. Requieren conectar una herramienta de on-call (PagerDuty/Opsgenie), en roadmap. Rol: TL/Director. Acción: seguir tendencia y tiempo de resolución.",
        role: "Director",
        importance: "media",
      },
      {
        id: "met-reabiertas",
        q: "Historias reabiertas",
        a: "Qué es: tareas dadas por terminadas que vuelven a abrirse. Importan como señal de calidad o mal refinamiento. Si suben, faltó definición de terminado; si bajan, mejor calidad. Rol: PO/TL. Acción: reforzar criterios de aceptación.",
        role: "PO",
        importance: "media",
        featured: ["PO"],
      },
      {
        id: "met-score-salud",
        q: "Score de salud",
        a: "Qué es: indicador compuesto de 0 a 100 que resume avance, calidad, ritmo y riesgos del período. Importa para saber de un vistazo cómo viene todo. Si baja, algo se deterioró; si sube, va bien. Rol: Todos. Acción: usarlo como punto de partida de la lectura.",
        role: "Director",
        importance: "alta",
        featured: ["Director"],
      },
      {
        id: "met-riesgo-sprint",
        q: "Riesgo del sprint",
        a: "Qué es: nivel de probabilidad de no cumplir el compromiso, según bloqueos, scope y ritmo. Importa para actuar a tiempo. Si sube, intervenir ya; si baja, sostener. Rol: TL/PO/Scrum. Acción: priorizar y desbloquear.",
        role: "TL",
        importance: "alta",
      },
      {
        id: "met-predictibilidad",
        q: "Predictibilidad",
        a: "Qué es: qué tan estable es el equipo en cumplir lo que planifica sprint a sprint. Importa más que la velocidad pico. Si baja, hay inconsistencia; si sube, se puede comprometer con confianza. Rol: Director/PO. Acción: estabilizar antes que acelerar.",
        role: "Director",
        importance: "alta",
        featured: ["Director"],
      },
      {
        id: "met-participacion",
        q: "Participación del equipo",
        a: "Qué es: proxy de cuán distribuida está la actividad entre las personas. Importa para detectar sobrecarga o desconexión. Leerla con cuidado: es señal, no juicio. Rol: TL. Acción: abrir conversación, no sacar conclusiones solo/a con el dato.",
        role: "TL",
        importance: "media",
      },
      {
        id: "met-comunicacion-bloqueos",
        q: "Comunicación de bloqueos",
        a: "Qué es: qué tan temprano se visibilizan los impedimentos. Importa porque un bloqueo dicho a tiempo se resuelve barato. Si mejora, hay buena cultura; si empeora, se descubren tarde. Rol: TL/Scrum. Acción: fomentar avisar temprano.",
        role: "TL",
        importance: "media",
      },
      {
        id: "met-performance-individual",
        q: "Performance individual",
        a: "Qué es: síntesis por persona basada en proxies (tareas, PRs, review), pensada para acompañar, no para rankear. Importa para dar feedback con datos. Nunca es un veredicto automático. Rol: TL. Acción: usarla como insumo de un 1:1, con contexto.",
        role: "TL",
        importance: "alta",
        featured: ["TL"],
      },
    ],
  },
  {
    id: "alerts",
    title: "Alertas y riesgos",
    description: "Cómo se detectan las señales tempranas y qué hacer con ellas.",
    items: [
      {
        id: "ale-que-son",
        q: "¿Qué son las alertas?",
        a: "Señales tempranas que DevMetrics levanta cuando una métrica cruza un umbral o empeora entre sprints: bloqueos crecientes, scope creep, review lento, caída de ritmo, entre otras.",
        role: "Todos",
        importance: "alta",
      },
      {
        id: "ale-como-generan",
        q: "¿Cómo se generan?",
        a: "A partir de los datos del período y de la comparación con períodos anteriores. Cada alerta lleva una etiqueta de rol para que sepas a quién le corresponde mirarla.",
        role: "Todos",
        importance: "media",
      },
      {
        id: "ale-alto-riesgo",
        q: "¿Qué significa una alerta de alto riesgo?",
        a: "Que hay un factor con impacto probable en la entrega y conviene actuar este sprint. No es catastrófico todavía, pero ignorarla suele escalar el problema.",
        role: "Todos",
        importance: "alta",
      },
      {
        id: "ale-critica",
        q: "¿Qué significa una alerta crítica?",
        a: "Que el impacto es alto e inmediato (por ejemplo, el build roto por días o muchos bloqueos sin movimiento). Requiere atención hoy y probablemente escalamiento.",
        role: "Todos",
        importance: "alta",
      },
      {
        id: "ale-recurrente",
        q: "¿Qué significa una alerta recurrente?",
        a: "Que la misma señal aparece en varios sprints seguidos. Deja de ser un evento puntual y pasa a ser un patrón que conviene atacar de raíz, no solo mitigar.",
        role: "TL",
        importance: "media",
      },
      {
        id: "ale-prioridad",
        q: "¿Cómo se priorizan las alertas?",
        a: "Por severidad e impacto en la entrega: primero críticas, luego alto riesgo, luego el resto. La vista ejecutiva ya te muestra las más importantes arriba.",
        role: "Director",
        importance: "media",
      },
      {
        id: "ale-resolver",
        q: "¿Cómo se resuelve una alerta?",
        a: "Actuando sobre su causa (desbloquear, repriorizar, sumar reviewers) y marcando el reporte como revisado. En el próximo período verás si la señal bajó.",
        role: "Todos",
        importance: "media",
      },
      {
        id: "ale-quien-revisa",
        q: "¿Quién debería revisar cada alerta?",
        a: "La etiqueta de rol lo indica: bloqueos y review para el TL, scope y valor para el PO, salud y previsibilidad para Dirección. Así nadie mira lo que no le toca.",
        role: "Todos",
        importance: "media",
      },
      {
        id: "ale-no-atendida",
        q: "¿Qué pasa si una alerta no se atiende?",
        a: "Si la causa persiste, la alerta reaparece y suele escalar de severidad. DevMetrics la marca como recurrente para que quede claro que el problema se está sosteniendo.",
        role: "Todos",
        importance: "media",
      },
      {
        id: "ale-personalizar",
        q: "¿Puedo configurar alertas personalizadas?",
        a: "Hoy las alertas se basan en umbrales pensados por defecto para equipos ágiles. Umbrales y reglas personalizables por workspace están en el roadmap; contanos qué necesitás para priorizarlo.",
        role: "Admin",
        importance: "baja",
      },
      {
        id: "ale-sprint-riesgo",
        q: "¿Cómo sé si un sprint está en riesgo?",
        a: "El score de salud y el nivel de riesgo del sprint lo resumen, y las alertas explican por qué. Un sprint con muchos bloqueos, scope creciente y ritmo en baja es la combinación típica.",
        role: "TL",
        importance: "alta",
      },
      {
        id: "ale-detectar-bloqueos",
        q: "¿Cómo detecto bloqueos antes de que impacten?",
        a: "DevMetrics marca tareas trabadas y cuánto llevan sin movimiento, y levanta alerta cuando crecen. Revisarlas en la daily te permite desbloquear temprano, cuando cuesta poco.",
        role: "TL",
        importance: "alta",
        featured: ["TL"],
      },
      {
        id: "ale-deterioro",
        q: "¿Cómo identifico deterioro entre sprints?",
        a: "La comparación clasifica cada métrica como mejora, estable o deterioro y levanta alertas cuando algo empeora sostenidamente. Es la mejor herramienta para retros.",
        role: "TL",
        importance: "media",
      },
      {
        id: "ale-tecnico-vs-producto",
        q: "¿Cómo diferencio un riesgo técnico de uno de producto?",
        a: "Los riesgos técnicos vienen de código, review, CI y bloqueos (rol TL); los de producto, de scope, valor entregado e historias reabiertas (rol PO). Cada alerta ya viene etiquetada.",
        role: "Todos",
        importance: "media",
      },
      {
        id: "ale-escalar",
        q: "¿Cómo escalo una alerta a dirección?",
        a: "Compartiendo el reporte con la lectura ejecutiva, donde la alerta aparece con su impacto y contexto. Dirección ve el riesgo sin necesidad de entrar al detalle técnico.",
        role: "Director",
        importance: "media",
      },
    ],
  },
  {
    id: "role-tl",
    title: "Para Tech Leads",
    description: "Lo que un TL debería mirar y cómo usarlo en el día a día.",
    items: [
      {
        id: "tl-primero",
        q: "¿Qué información debería revisar primero?",
        a: "El nivel de riesgo del sprint y las alertas técnicas: bloqueos, PRs demorados y estado de CI. Son lo que más rápido impacta la entrega.",
        role: "TL",
        importance: "alta",
        featured: ["TL"],
      },
      {
        id: "tl-reportes-tecnicos",
        q: "¿Qué reportes técnicos son más importantes?",
        a: "La lectura técnica del reporte (PRs, tiempo de review, CI) y la comparación entre sprints para ver si la calidad y el flujo mejoran o se deterioran.",
        role: "TL",
        importance: "media",
      },
      {
        id: "tl-deuda",
        q: "¿Cómo detecto deuda técnica?",
        a: "Con señales indirectas: historias reabiertas, bugs recurrentes y builds inestables. La medición directa (cobertura, code smells) requiere conectar Codecov/Sonar, en roadmap.",
        role: "TL",
        importance: "media",
      },
      {
        id: "tl-prs-demorados",
        q: "¿Cómo veo PRs demorados?",
        a: "El reporte lista los PRs abiertos y su tiempo de review, y alerta cuando se acumulan. Así identificás cuellos de botella y a quién falta liberar carga de review.",
        role: "TL",
        importance: "alta",
        featured: ["TL"],
      },
      {
        id: "tl-bloqueos",
        q: "¿Cómo veo bloqueos técnicos?",
        a: "En el detalle de tareas bloqueadas, con cuánto tiempo llevan detenidas. Ideal para atacarlos en la daily antes de que arrastren al resto del sprint.",
        role: "TL",
        importance: "alta",
      },
      {
        id: "tl-acompanamiento",
        q: "¿Cómo identifico personas que necesitan acompañamiento?",
        a: "El desempeño por persona señala, con proxies y siempre como hipótesis, quién podría estar sobrecargado o trabado. Es un insumo para conversar en un 1:1, no un veredicto.",
        role: "TL",
        importance: "alta",
        featured: ["TL"],
      },
      {
        id: "tl-calidad",
        q: "¿Cómo uso la app para mejorar calidad?",
        a: "Siguiendo bugs, historias reabiertas y estabilidad de CI a lo largo de los sprints. La tendencia te dice si las mejoras que aplicás están funcionando.",
        role: "TL",
        importance: "media",
      },
      {
        id: "tl-ceremonias",
        q: "¿Cómo la uso en la daily o la retro?",
        a: "En la daily, para repasar bloqueos y PRs demorados; en la retro, la comparación entre sprints te da datos concretos sobre qué mejoró y qué empeoró, sin depender de percepciones.",
        role: "TL",
        importance: "media",
      },
    ],
  },
  {
    id: "role-po",
    title: "Para Product Owners",
    description: "Cómo saber si el sprint entrega valor y comunicar estado.",
    items: [
      {
        id: "po-valor",
        q: "¿Cómo sé si el sprint está entregando valor?",
        a: "Mirando completion rate, historias efectivamente cerradas y scope creep juntos: mucho movimiento con poco cerrado, o alcance que crece, son señales de que el valor entregado está en riesgo.",
        role: "PO",
        importance: "alta",
        featured: ["PO"],
      },
      {
        id: "po-scope-creep",
        q: "¿Cómo veo el scope creep?",
        a: "El reporte muestra cuánto trabajo se sumó después de iniciado el sprint. Si es alto, conviene revisar cómo entra el trabajo y proteger mejor el compromiso.",
        role: "PO",
        importance: "alta",
        featured: ["PO"],
      },
      {
        id: "po-refinamiento",
        q: "¿Cómo sé si las historias están bien refinadas?",
        a: "Historias reabiertas, mucho carry over y alta variabilidad de cierre suelen indicar refinamiento flojo o criterios de aceptación poco claros.",
        role: "PO",
        importance: "media",
      },
      {
        id: "po-reabiertas",
        q: "¿Cómo identifico historias reabiertas?",
        a: "El reporte las marca aparte. Un número que sube te avisa que algo se da por terminado sin estarlo: buen momento para reforzar la definición de terminado.",
        role: "PO",
        importance: "media",
      },
      {
        id: "po-backlog",
        q: "¿Cómo priorizo el backlog usando los reportes?",
        a: "Usá las señales de riesgo y valor para decidir qué entra al próximo sprint: si hay deterioro de calidad o bloqueos recurrentes, quizá convenga estabilizar antes de sumar features.",
        role: "PO",
        importance: "media",
      },
      {
        id: "po-demo",
        q: "¿Cómo preparo una demo?",
        a: "El reporte te da lo entregado en el período de forma ordenada, listo para mostrar. Evitás rearmar la lista a mano y llegás con datos de respaldo.",
        role: "PO",
        importance: "baja",
      },
      {
        id: "po-riesgos-producto",
        q: "¿Cómo detecto riesgos de producto?",
        a: "Con las alertas etiquetadas como riesgo de producto: scope descontrolado, valor entregado en baja o historias que vuelven. Son distintas de los riesgos técnicos y te tocan a vos.",
        role: "PO",
        importance: "alta",
      },
      {
        id: "po-stakeholders",
        q: "¿Cómo comunico el estado a los stakeholders?",
        a: "Compartiendo la lectura ejecutiva del reporte: salud, riesgos y tendencia, sin ruido técnico. Podés enviarla por email o programarla para que llegue sola.",
        role: "PO",
        importance: "media",
        featured: ["PO"],
      },
    ],
  },
  {
    id: "role-dir",
    title: "Para Directores y Gerentes",
    description: "Vista ejecutiva, portafolio de proyectos y decisiones.",
    items: [
      {
        id: "dir-vista",
        q: "¿Qué vista ejecutiva debería revisar?",
        a: "La lectura ejecutiva del reporte y el panel de salud por proyecto: te dan el estado general sin entrar al detalle técnico, resaltando lo que necesita decisión.",
        role: "Director",
        importance: "alta",
        featured: ["Director"],
      },
      {
        id: "dir-semaforo",
        q: "¿Cómo interpreto el semáforo general?",
        a: "Cada proyecto tiene un nivel de salud (saludable, estable, en observación, alto riesgo, crítico). Enfocás tu atención en los que están en rojo o ámbar; los verdes solo necesitan seguimiento.",
        role: "Director",
        importance: "alta",
        featured: ["Director"],
      },
      {
        id: "dir-proyectos-riesgo",
        q: "¿Cómo sé qué proyectos están en riesgo?",
        a: "El panel de salud por proyecto los ordena por score. Los de alto riesgo o críticos aparecen destacados para que no tengas que buscarlos uno por uno.",
        role: "Director",
        importance: "alta",
      },
      {
        id: "dir-previsibilidad",
        q: "¿Cómo detecto equipos con baja previsibilidad?",
        a: "La métrica de predictibilidad muestra qué equipos cumplen de forma estable lo que planifican. Baja previsibilidad, aunque la velocidad sea alta, es una señal de gestión importante.",
        role: "Director",
        importance: "media",
        featured: ["Director"],
      },
      {
        id: "dir-tendencias",
        q: "¿Cómo veo tendencias mensuales?",
        a: "Con los atajos por mes, 3 meses, 6 meses y año podés ver la evolución de la salud y las métricas clave, ideal para reuniones de seguimiento y reportes trimestrales.",
        role: "Director",
        importance: "media",
      },
      {
        id: "dir-decisiones",
        q: "¿Cómo sé dónde hace falta tomar decisiones?",
        a: "Las alertas críticas y de alto riesgo, junto con el deterioro sostenido entre períodos, marcan dónde tu intervención tiene más impacto.",
        role: "Director",
        importance: "media",
      },
      {
        id: "dir-compartir",
        q: "¿Cómo comparto reportes ejecutivos?",
        a: "Por email o compartiendo el reporte con la vista ejecutiva. Podés programarlos para que lleguen automáticamente a tu comité o a tus stakeholders.",
        role: "Director",
        importance: "media",
      },
      {
        id: "dir-multi-equipo",
        q: "¿Cómo la uso para seguir varios equipos?",
        a: "Con el multi-proyecto del plan Pro, cada equipo o cliente es un proyecto y el panel de salud te da la foto del portafolio completo en una pantalla.",
        role: "Director",
        importance: "alta",
        featured: ["Director"],
      },
    ],
  },
  {
    id: "people",
    title: "Personas y performance del equipo",
    description:
      "Cómo DevMetrics mira a las personas: con criterio humano, para acompañar y no para castigar.",
    items: [
      {
        id: "peo-como-analiza",
        q: "¿Cómo analiza la app la performance individual?",
        a: "A partir de proxies observables (tareas, PRs, tiempos de review, actividad) que combina en un perfil por persona. Es un punto de partida para conversar, nunca una calificación definitiva.",
        role: "TL",
        importance: "alta",
      },
      {
        id: "peo-evalua-auto",
        q: "¿La app evalúa a las personas automáticamente?",
        a: "No emite veredictos. Ofrece señales e hipótesis con contexto; la interpretación y la decisión siempre quedan en la persona líder. La herramienta acompaña, no juzga.",
        role: "TL",
        importance: "alta",
        featured: ["TL"],
      },
      {
        id: "peo-datos",
        q: "¿Qué datos se usan para analizar el desempeño?",
        a: "Solo datos de trabajo que ya existen en tus herramientas: actividad en tareas y código, tiempos de flujo y participación. No usamos contenido de conversaciones privadas.",
        role: "TL",
        importance: "media",
        featured: ["seguridad"],
      },
      {
        id: "peo-injustas",
        q: "¿Cómo evita conclusiones injustas?",
        a: "Presenta los datos como proxies con posibles explicaciones (vacaciones, tareas grandes, trabajo no medible) y solo levanta alerta tras varios sprints, no por un mal período aislado.",
        role: "TL",
        importance: "alta",
      },
      {
        id: "peo-destacadas",
        q: "¿Cómo identifico personas destacadas?",
        a: "El perfil marca contribuciones sostenidas por encima de lo esperado. Sirve para reconocer y también para cuidar que no se sobrecarguen.",
        role: "TL",
        importance: "media",
      },
      {
        id: "peo-podrian-mas",
        q: "¿Cómo identifico a quienes podrían dar más?",
        a: "Con señales de baja actividad relativa sostenida, siempre como hipótesis a validar. Muchas veces la causa es contexto (bloqueos, tareas mal asignadas), no falta de compromiso.",
        role: "TL",
        importance: "media",
      },
      {
        id: "peo-necesitan-apoyo",
        q: "¿Cómo identifico a quienes necesitan acompañamiento?",
        a: "El perfil sugiere posibles casos y propone pasos de coaching. La lectura correcta es “acá hay algo para conversar”, no “esta persona rinde mal”.",
        role: "TL",
        importance: "alta",
        featured: ["TL"],
      },
      {
        id: "peo-baja-participacion",
        q: "¿Cómo interpreto una alerta de baja participación?",
        a: "Como una invitación a preguntar, no como una acusación. Puede reflejar bloqueos, trabajo no registrado o sobrecarga en otra área. El paso siguiente es siempre una conversación.",
        role: "TL",
        importance: "media",
      },
      {
        id: "peo-contexto",
        q: "¿Cómo diferencio bajo rendimiento de falta de contexto?",
        a: "DevMetrics muestra hipótesis de contexto junto al dato para que no saques conclusiones apresuradas. La diferencia real la aportás vos, que conocés la situación de la persona.",
        role: "TL",
        importance: "alta",
      },
      {
        id: "peo-feedback",
        q: "¿Cómo uso los datos para dar feedback?",
        a: "Como respaldo objetivo de una conversación, no como su reemplazo. Los datos abren el tema; el acompañamiento y el criterio humano lo resuelven.",
        role: "TL",
        importance: "media",
      },
      {
        id: "peo-1a1",
        q: "¿Cómo uso los reportes en un 1:1?",
        a: "El perfil por persona resume evolución y propone pasos concretos de acompañamiento. Sirve para llegar preparado/a y enfocar la charla en apoyo, no en control.",
        role: "TL",
        importance: "media",
        featured: ["TL"],
      },
      {
        id: "peo-privacidad",
        q: "¿Cómo se protege la privacidad del equipo?",
        a: "Los perfiles solo son visibles para roles con permiso, se basan en datos de trabajo y no exponen conversaciones privadas. El enfoque es acompañamiento, no vigilancia.",
        role: "Admin",
        importance: "alta",
        featured: ["seguridad"],
      },
      {
        id: "peo-no-castigo",
        q: "¿Cómo evito que las métricas se usen como castigo?",
        a: "El diseño ayuda: proxies en vez de veredictos, hipótesis de contexto y alertas solo tras patrones sostenidos. Aun así, el uso responsable depende de la cultura del equipo; recomendamos tratarlas como apoyo.",
        role: "TL",
        importance: "alta",
      },
      {
        id: "peo-evolucion",
        q: "¿Cómo mido la evolución entre sprints?",
        a: "El perfil categoriza cómo evoluciona cada persona período a período (mejora, se sostiene, baja), para ver si el acompañamiento está funcionando.",
        role: "TL",
        importance: "media",
      },
      {
        id: "peo-repite",
        q: "¿Cómo sé si una alerta se repite?",
        a: "DevMetrics marca las señales que persisten en varios sprints. Una alerta puntual puede ser ruido; una sostenida merece una conversación de acompañamiento.",
        role: "TL",
        importance: "media",
      },
    ],
  },
  {
    id: "security",
    title: "Privacidad, seguridad y permisos",
    description: "Qué guardamos, qué no, y cómo cuidamos tu información.",
    items: [
      {
        id: "sec-almacena",
        q: "¿Qué datos almacena DevMetrics?",
        a: "Guardamos las métricas y los reportes generados, y las credenciales de integración de forma encriptada. Trabajamos con la mínima cantidad de datos necesaria para construir el reporte.",
        role: "Admin",
        importance: "alta",
        featured: ["seguridad"],
      },
      {
        id: "sec-no-almacena",
        q: "¿Qué datos NO almacena?",
        a: "No guardamos tu código fuente ni el contenido de conversaciones privadas. De comunicación usamos señales de actividad, no los mensajes.",
        role: "Admin",
        importance: "alta",
        featured: ["seguridad"],
      },
      {
        id: "sec-codigo",
        q: "¿La app accede al código fuente?",
        a: "No lo almacenamos. Leemos metadatos de código (PRs, commits, tiempos, CI) para las métricas, pero no guardamos el contenido de tus repositorios.",
        role: "Admin",
        importance: "alta",
        featured: ["seguridad"],
      },
      {
        id: "sec-conversaciones",
        q: "¿La app lee conversaciones privadas?",
        a: "No. De Slack, Teams o Discord tomamos señales de actividad y comunicación de bloqueos, no el texto de los mensajes privados.",
        role: "Admin",
        importance: "alta",
        featured: ["seguridad"],
      },
      {
        id: "sec-modifica",
        q: "¿Puede modificar información en Jira, GitHub o Slack?",
        a: "No. Todas las integraciones son de solo lectura. DevMetrics nunca crea, edita ni borra nada en tus herramientas.",
        role: "Admin",
        importance: "alta",
        featured: ["seguridad"],
      },
      {
        id: "sec-permisos",
        q: "¿Cómo se manejan los permisos?",
        a: "Por rol y por membresía de proyecto. Cada persona accede solo a los proyectos y reportes que le corresponden dentro del workspace.",
        role: "Admin",
        importance: "media",
      },
      {
        id: "sec-quien-ve",
        q: "¿Quién puede ver cada reporte?",
        a: "Los miembros del proyecto y las personas con quienes lo compartas explícitamente. Los reportes no son públicos por defecto.",
        role: "Admin",
        importance: "media",
      },
      {
        id: "sec-limitar-rol",
        q: "¿Cómo limito el acceso por rol?",
        a: "Asignando roles a los miembros del workspace. Las lecturas sensibles (como desempeño por persona) quedan reservadas a los roles con permiso.",
        role: "Admin",
        importance: "media",
        featured: ["seguridad"],
      },
      {
        id: "sec-eliminar-integracion",
        q: "¿Cómo elimino una integración?",
        a: "Desde Integraciones podés desconectarla en cualquier momento. Al hacerlo dejamos de leer esa fuente y se revoca el token guardado.",
        role: "Admin",
        importance: "media",
      },
      {
        id: "sec-eliminar-workspace",
        q: "¿Cómo elimino un workspace?",
        a: "Desde Ajustes, un admin puede eliminar el workspace. La acción borra sus proyectos, integraciones y reportes asociados.",
        role: "Admin",
        importance: "media",
      },
      {
        id: "sec-exportar",
        q: "¿Cómo exporto mis datos?",
        a: "Podés exportar reportes a CSV cuando quieras, así conservás tu información fuera de la plataforma.",
        role: "Admin",
        importance: "media",
      },
      {
        id: "sec-borrar",
        q: "¿Cómo borro mis datos?",
        a: "Eliminando integraciones, proyectos o el workspace completo. Los datos asociados dejan de estar disponibles al borrar el recurso que los contiene.",
        role: "Admin",
        importance: "media",
      },
      {
        id: "sec-proteccion",
        q: "¿Cómo se protege la información?",
        a: "Las credenciales de integración se guardan encriptadas (AES-256-GCM) y nunca se exponen al navegador. La comunicación viaja cifrada y aplicamos control de acceso por rol.",
        role: "Admin",
        importance: "alta",
        featured: ["seguridad"],
      },
      {
        id: "sec-buenas-practicas",
        q: "¿Cumple con buenas prácticas de seguridad?",
        a: "Seguimos principios de mínimo privilegio, solo lectura, cifrado de secretos y separación de accesos por rol. Para requisitos de cumplimiento específicos, escribinos desde Contacto.",
        role: "Admin",
        importance: "media",
        featured: ["seguridad"],
      },
      {
        id: "sec-info-sensible",
        q: "¿Se puede usar en empresas con información sensible?",
        a: "Sí, teniendo en cuenta que no almacenamos código ni mensajes y que todo acceso es de solo lectura y por rol. Para necesidades avanzadas de compliance, conversemos según tu caso.",
        role: "Director",
        importance: "media",
      },
      {
        id: "sec-usuario-sale",
        q: "¿Qué pasa cuando un usuario deja el equipo?",
        a: "Un admin lo quita del workspace y esa persona pierde el acceso a proyectos y reportes de inmediato. Los reportes ya generados permanecen en el workspace.",
        role: "Admin",
        importance: "media",
      },
    ],
  },
  {
    id: "plans",
    title: "Planes, precios y límites",
    description: "Qué incluye cada plan y cómo cambiarlo.",
    items: [
      {
        id: "pla-prueba",
        q: "¿Hay prueba gratuita?",
        a: "Mejor: hay un plan Free gratis para siempre, sin tarjeta, que ya conecta Jira + GitHub en vivo y genera reportes reales.",
        role: "Todos",
        importance: "alta",
        featured: ["nuevos"],
      },
      {
        id: "pla-incluye",
        q: "¿Qué incluye cada plan?",
        a: "Free: 1 proyecto, 5 usuarios, Jira + GitHub, reportes con lecturas por rol y export CSV. Team: hasta 45 usuarios, todas las integraciones de tareas y código, capacidad/velocity/calidad/CI, alertas, desempeño y envío por email. Pro: multi-proyecto, usuarios ilimitados, comunicación (Slack/Teams/Discord) y análisis con IA.",
        role: "Admin",
        importance: "alta",
        featured: ["nuevos"],
      },
      {
        id: "pla-limites",
        q: "¿Qué límites tiene cada plan?",
        a: "Los límites principales son proyectos, usuarios e integraciones disponibles. Free y Team trabajan sobre 1 proyecto; el multi-proyecto es exclusivo de Pro.",
        role: "Admin",
        importance: "media",
      },
      {
        id: "pla-usuarios",
        q: "¿Cuántos usuarios permite cada plan?",
        a: "Free hasta 5, Team hasta 45 y Pro usuarios ilimitados. El precio es plano por equipo: sumás gente sin costo por asiento.",
        role: "Admin",
        importance: "alta",
      },
      {
        id: "pla-proyectos",
        q: "¿Cuántos proyectos permite cada plan?",
        a: "Free y Team incluyen 1 proyecto. Pro es multi-proyecto (ilimitado), pensado para varias squads, equipos o clientes.",
        role: "Admin",
        importance: "media",
      },
      {
        id: "pla-integraciones",
        q: "¿Cuántas integraciones permite cada plan?",
        a: "Free: Jira + GitHub. Team: todas las de tareas y código. Pro: todas, incluidas comunicación (Slack/Teams/Discord) y los proveedores de IA.",
        role: "Admin",
        importance: "media",
      },
      {
        id: "pla-reportes-mes",
        q: "¿Hay límite de reportes mensuales?",
        a: "Podés generar reportes cuando los necesites. Los reportes automáticos programados se habilitan en Team y Pro.",
        role: "Admin",
        importance: "baja",
      },
      {
        id: "pla-automaticos",
        q: "¿Los reportes automáticos están en todos los planes?",
        a: "La programación automática está disponible desde el plan Team. En Free generás reportes de forma manual, sin límite práctico.",
        role: "Admin",
        importance: "media",
      },
      {
        id: "pla-export",
        q: "¿La exportación a PDF/CSV está en todos los planes?",
        a: "La exportación a CSV está disponible desde Free. Las opciones de envío y programación se amplían en Team y Pro.",
        role: "Admin",
        importance: "baja",
      },
      {
        id: "pla-soporte",
        q: "¿Qué soporte incluye cada plan?",
        a: "Todos los planes tienen soporte; el plan Pro suma soporte prioritario para equipos que dependen de la herramienta a diario.",
        role: "Admin",
        importance: "baja",
      },
      {
        id: "pla-diferencia-planes",
        q: "¿Cuál es la diferencia entre los planes?",
        a: "Free es para probar el valor con datos reales; Team es para todo un equipo con precio plano; Pro es para varias squads, con comunicación e IA. El salto clave a Pro es multi-proyecto + IA.",
        role: "Admin",
        importance: "media",
      },
      {
        id: "pla-anual",
        q: "¿Conviene el plan anual?",
        a: "Sí: pagando anual abonás 10 meses en lugar de 12, es decir dos meses gratis. El total anual se cobra por adelantado.",
        role: "Admin",
        importance: "media",
      },
      {
        id: "pla-cambiar",
        q: "¿Cómo cambio de plan?",
        a: "Desde Ajustes > Plan podés subir o bajar de plan cuando quieras. El cambio se refleja de inmediato en los límites y funcionalidades.",
        role: "Admin",
        importance: "media",
      },
      {
        id: "pla-cancelar",
        q: "¿Cómo cancelo la suscripción?",
        a: "Desde Ajustes > Plan podés cancelar o volver al plan Free en cualquier momento. No hay permanencia obligatoria.",
        role: "Admin",
        importance: "media",
      },
      {
        id: "pla-datos-cancelar",
        q: "¿Qué pasa con mis datos al cancelar?",
        a: "Conservás tu workspace en el plan Free; lo que exceda los límites del nuevo plan queda inactivo, no se borra automáticamente. Podés exportar a CSV antes de bajar de plan.",
        role: "Admin",
        importance: "media",
      },
      {
        id: "pla-empresas",
        q: "¿Hay planes para startups, consultoras o equipos grandes?",
        a: "El plan Pro cubre la mayoría de esos casos con multi-proyecto y usuarios ilimitados. Para necesidades a medida (varios workspaces, compliance), escribinos desde Contacto.",
        role: "Director",
        importance: "media",
      },
    ],
  },
  {
    id: "daily",
    title: "Uso diario",
    description: "Cómo integrar DevMetrics a tus ceremonias y a tu día a día.",
    items: [
      {
        id: "day-cada-dia",
        q: "¿Qué debería revisar al entrar cada día?",
        a: "Las alertas nuevas y los reportes pendientes de revisión. En dos minutos ves si algo cambió de estado y qué necesita tu atención hoy.",
        role: "Todos",
        importance: "media",
      },
      {
        id: "day-daily",
        q: "¿Cómo la uso en una daily?",
        a: "Abrí el reporte del sprint y repasá bloqueos y PRs demorados. Convierte la daily en una conversación enfocada en lo que realmente frena la entrega.",
        role: "TL",
        importance: "media",
      },
      {
        id: "day-planning",
        q: "¿Cómo la uso en un sprint planning?",
        a: "Mirá velocity, carry over y capacidad de sprints anteriores para comprometerte con un alcance realista, en vez de estimar de memoria.",
        role: "PO",
        importance: "media",
      },
      {
        id: "day-retro",
        q: "¿Cómo la uso en una retro?",
        a: "La comparación entre sprints te da datos objetivos sobre qué mejoró y qué empeoró, para que la retro se base en hechos y no solo en percepciones.",
        role: "TL",
        importance: "media",
      },
      {
        id: "day-demo",
        q: "¿Cómo la uso antes de una demo?",
        a: "El reporte del período ya te resume lo entregado, ordenado y con respaldo de datos. Llegás sin tener que armar la lista a mano.",
        role: "PO",
        importance: "baja",
      },
      {
        id: "day-ejecutiva",
        q: "¿Cómo la uso para una reunión ejecutiva?",
        a: "Compartí la lectura ejecutiva o el panel de salud por proyecto. Muestra estado, riesgos y tendencia sin ruido técnico, listo para dirección.",
        role: "Director",
        importance: "media",
      },
      {
        id: "day-hoy",
        q: "¿Cómo sé qué requiere atención hoy?",
        a: "Ordená por salud y mirá primero lo crítico y de alto riesgo. Las alertas destacadas te dicen exactamente dónde mirar.",
        role: "Todos",
        importance: "media",
      },
      {
        id: "day-revisado",
        q: "¿Cómo marco un reporte como revisado?",
        a: "Con la acción “marcar como revisado” en el reporte. Así el equipo sabe qué ya pasó por un responsable y qué queda pendiente.",
        role: "Todos",
        importance: "baja",
      },
      {
        id: "day-accion",
        q: "¿Cómo asigno una acción pendiente?",
        a: "Usando las notas del reporte para dejar registrado el próximo paso y a quién le corresponde. Queda como contexto para el seguimiento.",
        role: "Todos",
        importance: "baja",
      },
      {
        id: "day-insight",
        q: "¿Cómo comparto un insight con el equipo?",
        a: "Compartí el reporte o la nota puntual con los miembros del proyecto. Todos ven el mismo dato y la misma lectura.",
        role: "Todos",
        importance: "baja",
      },
      {
        id: "day-tarea-alerta",
        q: "¿Cómo creo una tarea a partir de una alerta?",
        a: "Hoy podés registrar el próximo paso como nota en el reporte. La creación directa de tareas en Jira/Slack desde una alerta está en el roadmap.",
        role: "TL",
        importance: "baja",
      },
      {
        id: "day-decision",
        q: "¿Cómo hago seguimiento de una decisión?",
        a: "Dejala anotada en el reporte y revisá en la comparación del próximo período si la métrica asociada mejoró. Así cerrás el ciclo con datos.",
        role: "Todos",
        importance: "baja",
      },
    ],
  },
  {
    id: "troubleshooting",
    title: "Errores y datos incompletos",
    description: "Qué mirar cuando algo no aparece o un reporte no cierra.",
    items: [
      {
        id: "tro-sin-datos",
        q: "¿Por qué un reporte puede aparecer sin datos?",
        a: "Casi siempre porque no hay integraciones conectadas para ese proyecto o el período elegido no tiene actividad. Verificá el estado en Integraciones y el rango de fechas.",
        role: "Admin",
        importance: "media",
      },
      {
        id: "tro-metrica-cero",
        q: "¿Por qué una métrica puede estar en cero?",
        a: "Porque su fuente no está conectada o no hubo actividad de ese tipo en el período. Por ejemplo, sin GitHub no hay métricas de PRs.",
        role: "Admin",
        importance: "media",
      },
      {
        id: "tro-sin-prs",
        q: "¿Por qué no aparecen PRs?",
        a: "Revisá que GitHub, GitLab o Bitbucket esté conectado y que los repos correctos estén en el alcance seleccionado. Un token sin permiso de lectura sobre esos repos también lo explica.",
        role: "Admin",
        importance: "media",
      },
      {
        id: "tro-sin-jira",
        q: "¿Por qué no aparecen tareas de Jira?",
        a: "Verificá que la integración esté conectada, que el proyecto de Jira esté dentro del alcance y que el token siga vigente. Reintentá la sincronización desde Integraciones.",
        role: "Admin",
        importance: "media",
      },
      {
        id: "tro-sin-slack",
        q: "¿Por qué no se sincronizó Slack o Teams?",
        a: "Suele deberse a que la autorización expiró o faltan canales seleccionados. Reconectá la integración y confirmá los canales a seguir. Recordá que es una función del plan Pro.",
        role: "Admin",
        importance: "baja",
      },
      {
        id: "tro-falla-integracion",
        q: "¿Por qué falló una integración?",
        a: "Los motivos más comunes son token vencido o revocado, permisos insuficientes o límite de la API alcanzado. DevMetrics te muestra el motivo para que sepas qué corregir.",
        role: "Admin",
        importance: "media",
      },
      {
        id: "tro-tarda",
        q: "¿Por qué un reporte tarda en generarse?",
        a: "Cuando hay muchas fuentes o mucho historial, leer todos los datos lleva un poco más. Si se demora de forma inusual, puede ser un límite temporal de alguna API; reintentá en unos minutos.",
        role: "Admin",
        importance: "baja",
      },
      {
        id: "tro-incorrecto",
        q: "¿Qué hago si un reporte parece incorrecto?",
        a: "Confirmá qué fuentes están conectadas y su alcance: la mayoría de las diferencias vienen de datos que faltan por una integración desconectada. Si el dato sigue sin cerrar, escribinos a soporte.",
        role: "Admin",
        importance: "media",
      },
      {
        id: "tro-resync",
        q: "¿Cómo reintento la sincronización?",
        a: "Desde Integraciones, con “probar conexión” y forzar resincronización. Es el primer paso ante casi cualquier dato faltante o desactualizado.",
        role: "Admin",
        importance: "media",
      },
      {
        id: "tro-reportar",
        q: "¿Cómo reporto un problema?",
        a: "Desde Contacto o soporte, contándonos qué esperabas ver y qué viste. Cuanto más contexto (proyecto, período, integración), más rápido lo resolvemos.",
        role: "Todos",
        importance: "media",
      },
      {
        id: "tro-soporte",
        q: "¿Cómo contacto a soporte?",
        a: "Desde el formulario de Contacto. Los planes Pro cuentan con soporte prioritario.",
        role: "Todos",
        importance: "media",
      },
      {
        id: "tro-estado-integraciones",
        q: "¿Cómo reviso el estado de las integraciones?",
        a: "En Integraciones ves cada fuente con su estado (conectada, desconectada, con error) y podés probar la conexión al instante.",
        role: "Admin",
        importance: "media",
      },
      {
        id: "tro-datos-insuficientes",
        q: "¿Qué significa “datos insuficientes”?",
        a: "Que no hay suficiente información conectada o de historial para calcular esa métrica o comparación de forma confiable. Se resuelve conectando la fuente o esperando más períodos.",
        role: "Admin",
        importance: "media",
      },
      {
        id: "tro-generacion-fallida",
        q: "¿Qué significa “generación fallida”?",
        a: "Que el reporte no pudo completarse, normalmente por una integración con error durante la lectura. Revisá el estado de las fuentes y reintentá; si persiste, avisá a soporte.",
        role: "Admin",
        importance: "media",
      },
    ],
  },
  {
    id: "customization",
    title: "Personalización",
    description: "Qué podés adaptar a tu equipo hoy y qué está en el roadmap.",
    items: [
      {
        id: "cus-reportes",
        q: "¿Puedo personalizar los reportes?",
        a: "Sí, en buena medida: elegís período, filtrás por rol, fijás y etiquetás reportes, y sumás notas. Plantillas totalmente personalizables están en el roadmap.",
        role: "Admin",
        importance: "media",
      },
      {
        id: "cus-metricas",
        q: "¿Puedo personalizar las métricas?",
        a: "Las métricas vienen curadas para equipos ágiles. Elegís qué fuentes conectás (y por lo tanto qué métricas aparecen); la definición de métricas propias está en evaluación.",
        role: "Admin",
        importance: "baja",
      },
      {
        id: "cus-alertas",
        q: "¿Puedo crear alertas propias?",
        a: "Hoy las alertas usan umbrales por defecto pensados para la mayoría de los equipos. Reglas y umbrales personalizables están en el roadmap.",
        role: "Admin",
        importance: "baja",
      },
      {
        id: "cus-kpis-rol",
        q: "¿Puedo elegir KPIs por rol?",
        a: "Las lecturas por rol ya priorizan los KPIs relevantes para TL, PO y Dirección de forma automática, así cada quien ve lo suyo sin configurar nada.",
        role: "Todos",
        importance: "media",
      },
      {
        id: "cus-vistas",
        q: "¿Puedo guardar vistas?",
        a: "Podés fijar reportes y usar los atajos de período. El guardado de vistas y filtros personalizados está en el roadmap.",
        role: "Admin",
        importance: "baja",
      },
      {
        id: "cus-plantillas",
        q: "¿Puedo crear plantillas?",
        a: "Las plantillas de reporte configurables están en el roadmap. Hoy el formato del reporte es consistente y ya se adapta al rol de quien lo lee.",
        role: "Admin",
        importance: "baja",
      },
      {
        id: "cus-recurrentes",
        q: "¿Puedo configurar reportes recurrentes?",
        a: "Sí, en Team y Pro. Definís la frecuencia y DevMetrics genera y envía el reporte automáticamente.",
        role: "Admin",
        importance: "media",
      },
      {
        id: "cus-permisos",
        q: "¿Puedo personalizar los permisos?",
        a: "Sí, mediante roles y membresía de proyecto. Definís quién ve qué proyectos y quién accede a lecturas sensibles como desempeño por persona.",
        role: "Admin",
        importance: "media",
      },
      {
        id: "cus-idioma",
        q: "¿Puedo cambiar el idioma?",
        a: "La interfaz está en español. El soporte multi-idioma (empezando por inglés) está en el roadmap; contanos qué idioma necesitás para priorizarlo.",
        role: "Todos",
        importance: "baja",
      },
      {
        id: "cus-ocultar",
        q: "¿Puedo ocultar métricas sensibles?",
        a: "Sí: las lecturas sensibles se controlan por rol, así ciertas métricas (como desempeño individual) solo las ven los perfiles habilitados.",
        role: "Admin",
        importance: "media",
      },
      {
        id: "cus-score-propio",
        q: "¿Puedo definir un score de salud propio?",
        a: "El score usa una fórmula balanceada por defecto. Poder ajustar sus pesos por workspace está en el roadmap; escribinos si es clave para tu equipo.",
        role: "Admin",
        importance: "baja",
      },
      {
        id: "cus-tags",
        q: "¿Puedo agregar tags a los reportes?",
        a: "Sí. Podés etiquetar reportes para organizarlos y encontrarlos después (por cliente, hito, tipo de sprint, etc.).",
        role: "Admin",
        importance: "baja",
      },
    ],
  },
  {
    id: "ai",
    title: "IA e interpretación automática",
    description: "Cómo usamos IA, qué analiza y cómo la mantenemos bajo tu control.",
    items: [
      {
        id: "ai-como-usa",
        q: "¿Cómo usa IA DevMetrics?",
        a: "En el plan Pro, la IA analiza los datos del reporte para redactar insights, resaltar riesgos y sugerir acciones, y te deja un espacio para “preguntarle al reporte” en lenguaje natural.",
        role: "Director",
        importance: "media",
      },
      {
        id: "ai-que-analiza",
        q: "¿Qué analiza la IA?",
        a: "Solo la información que ya se presenta en el reporte: métricas, tendencias y alertas del período. No inventa datos externos ni accede a fuentes por fuera de lo conectado.",
        role: "Todos",
        importance: "alta",
      },
      {
        id: "ai-decisiones",
        q: "¿La IA toma decisiones automáticamente?",
        a: "No. Sugiere y explica; nunca ejecuta acciones ni cambia nada por su cuenta. Las decisiones quedan siempre en las personas.",
        role: "Todos",
        importance: "alta",
      },
      {
        id: "ai-reemplaza",
        q: "¿La IA reemplaza al TL, PO o Director?",
        a: "No. Acelera la lectura y aporta una segunda mirada, pero el criterio, el contexto y la decisión son tuyos. Es un copiloto, no un reemplazo.",
        role: "Todos",
        importance: "media",
      },
      {
        id: "ai-insights",
        q: "¿Cómo se generan los insights?",
        a: "La IA recibe las métricas y alertas del reporte y las resume en observaciones claras, priorizadas por impacto. Siempre parten de tus datos reales.",
        role: "Todos",
        importance: "media",
      },
      {
        id: "ai-recomendaciones",
        q: "¿Cómo se generan las recomendaciones?",
        a: "A partir de los patrones detectados en el período y su comparación con anteriores. Son sugerencias para tu consideración, no instrucciones a seguir a ciegas.",
        role: "Todos",
        importance: "media",
      },
      {
        id: "ai-patrones",
        q: "¿Cómo se detectan los patrones?",
        a: "Combinando las métricas del período con la evolución histórica: deterioros sostenidos, señales recurrentes y correlaciones entre indicadores.",
        role: "TL",
        importance: "baja",
      },
      {
        id: "ai-injustas",
        q: "¿Cómo se evitan conclusiones injustas?",
        a: "La IA trabaja sobre proxies y los presenta como hipótesis con contexto, especialmente al hablar de personas. Nunca emite veredictos sobre individuos.",
        role: "TL",
        importance: "alta",
        featured: ["TL"],
      },
      {
        id: "ai-editar",
        q: "¿Puedo editar una conclusión de la IA?",
        a: "El análisis es un insumo: podés ignorarlo, matizarlo o registrar tu propia lectura en las notas del reporte. Tu criterio prevalece.",
        role: "Todos",
        importance: "media",
      },
      {
        id: "ai-regenerar",
        q: "¿Puedo regenerar un análisis?",
        a: "Sí. Podés volver a generar el análisis o hacer una nueva pregunta al reporte cuando quieras otra perspectiva.",
        role: "Todos",
        importance: "baja",
      },
      {
        id: "ai-fuentes",
        q: "¿Puedo ver las fuentes de datos que usó?",
        a: "Sí: el análisis se apoya en las métricas y alertas visibles del reporte, así que podés contrastar cada afirmación con el dato que la respalda.",
        role: "Todos",
        importance: "media",
      },
      {
        id: "ai-equivoca",
        q: "¿La IA puede equivocarse?",
        a: "Sí. Es una ayuda de interpretación y puede malinterpretar el contexto. Por eso la presentamos como sugerencia y recomendamos validarla antes de actuar.",
        role: "Todos",
        importance: "alta",
      },
      {
        id: "ai-validar",
        q: "¿Cómo valido una recomendación antes de actuar?",
        a: "Contrastala con las métricas que la respaldan y con tu conocimiento del equipo. Si el dato y el contexto coinciden, avanzá; si no, tratala como hipótesis a chequear.",
        role: "Todos",
        importance: "media",
      },
    ],
  },
  {
    id: "commercial",
    title: "Valor y adopción",
    description: "Por qué usar DevMetrics y cómo mostrar su valor a tu equipo.",
    items: [
      {
        id: "com-ya-jira",
        q: "¿Por qué usar DevMetrics si ya tengo Jira?",
        a: "Jira registra el trabajo; DevMetrics lo interpreta y lo cruza con código, CI y comunicación para decirte cómo viene realmente el sprint y qué decidir. Es la capa de lectura que Jira no te da.",
        role: "Todos",
        importance: "alta",
        featured: ["nuevos"],
      },
      {
        id: "com-ya-dashboards",
        q: "¿Por qué usar DevMetrics si ya tengo dashboards?",
        a: "Un dashboard te deja armar y mirar gráficos; DevMetrics los arma solo, los explica y sugiere acciones por rol. Menos tiempo configurando, más tiempo decidiendo.",
        role: "Todos",
        importance: "media",
      },
      {
        id: "com-vs-bi",
        q: "¿En qué se diferencia de una herramienta de BI?",
        a: "BI es genérico y requiere que vos definas modelos, consultas y visualizaciones. DevMetrics viene con el conocimiento de ingeniería incorporado: métricas ágiles, salud y riesgos listos, sin proyecto de datos previo.",
        role: "Director",
        importance: "media",
      },
      {
        id: "com-vs-manual",
        q: "¿En qué se diferencia de los reportes manuales?",
        a: "Los reportes manuales consumen horas, quedan desactualizados y dependen de quién los arma. DevMetrics los genera al instante, con datos consistentes y comparables período a período.",
        role: "Todos",
        importance: "media",
      },
      {
        id: "com-ahorro",
        q: "¿Cómo ayuda a ahorrar tiempo?",
        a: "Automatiza la recolección y el armado del estado del equipo. El tiempo que hoy se va en juntar datos y hacer capturas pasa a estar disponible para actuar.",
        role: "Todos",
        importance: "media",
      },
      {
        id: "com-previsibilidad",
        q: "¿Cómo ayuda a mejorar la previsibilidad?",
        a: "Al hacer visible la predictibilidad, el carry over y el scope creep, te permite comprometerte con alcances realistas y detectar temprano cuando algo se desvía.",
        role: "Director",
        importance: "media",
      },
      {
        id: "com-riesgos",
        q: "¿Cómo ayuda a reducir riesgos?",
        a: "Con alertas tempranas y comparación entre períodos, los problemas se ven antes de impactar la entrega, cuando resolverlos todavía es barato.",
        role: "Director",
        importance: "media",
      },
      {
        id: "com-tl",
        q: "¿Cómo ayuda a los líderes técnicos?",
        a: "Les da visibilidad inmediata de bloqueos, PRs demorados y calidad, y datos para acompañar a su equipo sin tener que rastrear todo a mano.",
        role: "TL",
        importance: "media",
      },
      {
        id: "com-po",
        q: "¿Cómo ayuda a los equipos de producto?",
        a: "Muestra si el sprint entrega valor, dónde se cuela scope y qué historias vuelven, para priorizar mejor y comunicar estado con respaldo.",
        role: "PO",
        importance: "media",
      },
      {
        id: "com-gerentes",
        q: "¿Cómo ayuda a los gerentes?",
        a: "Con una vista de portafolio: salud por proyecto, previsibilidad y tendencias, para saber dónde intervenir sin pedir reportes a cada equipo.",
        role: "Director",
        importance: "media",
      },
      {
        id: "com-convencer-equipo",
        q: "¿Cómo convenzo a mi equipo de usarla?",
        a: "Empezá gratis con Jira + GitHub y mostrá un reporte real en la próxima retro. El valor se ve solo cuando el equipo deja de armar el estado a mano.",
        role: "Todos",
        importance: "media",
      },
      {
        id: "com-presentar-direccion",
        q: "¿Cómo presento la app a dirección?",
        a: "Mostrales la lectura ejecutiva y el panel de salud por proyecto: entienden el estado del portafolio en un vistazo. Ese es el argumento más fuerte para dirección.",
        role: "Director",
        importance: "media",
        featured: ["Director"],
      },
      {
        id: "com-roi",
        q: "¿Cómo mido el ROI de la app?",
        a: "Compará el tiempo que dedicabas a armar reportes de estado con el actual, y el impacto de detectar riesgos antes. A eso se suma el precio plano por equipo, sin costo por asiento.",
        role: "Director",
        importance: "media",
      },
      {
        id: "com-tiempo-valor",
        q: "¿Cuánto tarda en mostrar valor?",
        a: "Desde el primer reporte ya ves avance, PRs, bloqueos y salud. El valor de comparación y tendencias aparece a los pocos sprints, cuando hay historial.",
        role: "Todos",
        importance: "media",
        featured: ["nuevos"],
      },
    ],
  },
];

export const FEATURED_GROUPS: { id: FeaturedGroup; title: string; description: string }[] = [
  {
    id: "nuevos",
    title: "Para empezar",
    description: "Las preguntas más frecuentes de quienes recién llegan.",
  },
  {
    id: "TL",
    title: "Destacadas para Tech Leads",
    description: "Lo primero que suele buscar un TL.",
  },
  {
    id: "PO",
    title: "Destacadas para Product Owners",
    description: "Valor del sprint, scope y comunicación.",
  },
  {
    id: "Director",
    title: "Destacadas para Dirección",
    description: "Vista ejecutiva, portafolio y decisiones.",
  },
  {
    id: "seguridad",
    title: "Seguridad y privacidad",
    description: "Lo esencial sobre tus datos y permisos.",
  },
];

// Índice plano de todos los items, útil para búsqueda y destacadas.
export interface FaqIndexItem extends FaqItem {
  categoryId: string;
  categoryTitle: string;
}

export const FAQ_INDEX: FaqIndexItem[] = FAQ.flatMap((cat) =>
  cat.items.map((item) => ({
    ...item,
    categoryId: cat.id,
    categoryTitle: cat.title,
  })),
);
